packages/dx-react-core/src/plugged/template-connector.jsx
packages/dx-react-core/src/plugged/template-placeholder.jsx

chore(react-core): extend components with shouldComponentUpdate from React.Component

---

packages/dx-react-grid-bootstrap3/src/templates/table-edit-cell.jsx
packages/dx-react-grid-bootstrap3/src/templates/table-edit-cell.test.jsx
packages/dx-react-grid-material-ui/src/templates/table-edit-cell.jsx
packages/dx-react-grid-material-ui/src/templates/table-edit-cell.test.jsx
packages/dx-react-grid/src/plugins/table-edit-row.jsx

fix(react-grid): pass style field to editCellTemplate of TableEditRow

---

packages/dx-react-grid-bootstrap3/src/plugins/table-view.jsx
packages/dx-react-grid-bootstrap3/src/plugins/virtual-table-view.jsx
packages/dx-react-grid-material-ui/src/plugins/table-view.jsx
packages/dx-react-grid/docs/reference/table-view.md
packages/dx-react-grid/src/plugins/table-group-row.test.jsx
packages/dx-react-grid/src/plugins/table-view.jsx
packages/dx-react-grid/src/plugins/table-view.test.jsx

This reverts commit 06af8bb905b34a449a14cccf1f83b1e4214d0e0a.

revert: TableView: tableTemplate -> tableLayoutTemplate

---

scripts/publish-npm.js

Related to: https://github.com/lerna/lerna/issues/266

chore: fix partial vesion update

---

packages/dx-grid-core/src/plugins/table-selection/computeds.js
packages/dx-grid-core/src/plugins/table-selection/computeds.test.js
packages/dx-react-grid/src/plugins/table-selection.jsx
packages/dx-react-grid/src/plugins/table-selection.test.jsx

fix(react-grid): optimize table selection rendering

---

packages/dx-react-demos/src/bootstrap3/featured-redux-integration/demo.jsx
packages/dx-react-demos/src/bootstrap3/virtual-scrolling/basic.ssr.test.jsx
packages/dx-react-demos/src/bootstrap3/virtual-scrolling/basic.test.jsx
packages/dx-react-demos/src/index.jsx
packages/dx-react-demos/src/material-ui/featured-redux-integration/demo.jsx
packages/dx-react-grid-bootstrap3/src/templates/virtual-table.jsx
packages/dx-react-grid-bootstrap3/src/templates/virtual-table/sizer.jsx
packages/dx-react-grid-bootstrap3/src/templates/virtual-table/virtual-box.jsx
packages/dx-react-grid-bootstrap3/src/templates/virtual-table/windowed-scroller.jsx

fix(react-grid-bootstrap3): fix server side rendering issue with VirtualTable

---

packages/dx-react-grid/src/components/table-layout/virtual-table-utils.js
packages/dx-react-grid/src/components/table-layout/virtual-table-utils.test.js

fix(react-grid): fix hidden tall rows in VirtualTable

---

packages/dx-react-grid/src/components/table-layout/virtual-table-layout.jsx

fix(react-grid): calculate visible rows when rendering VirtualTable

---

packages/dx-react-grid-bootstrap3/src/templates/table-cell.test.jsx
packages/dx-react-grid-bootstrap4/src/templates/table-cell.jsx
packages/dx-react-grid-bootstrap4/src/templates/table-cell.test.jsx
packages/dx-react-grid-bootstrap4/src/templates/table-edit-cell.jsx
packages/dx-react-grid-bootstrap4/src/templates/table-header-cell.jsx
packages/dx-react-grid-bootstrap4/src/templates/table-header-cell.test.jsx
packages/dx-react-grid-material-ui/src/templates/table-cell.jsx
packages/dx-react-grid-material-ui/src/templates/table-cell.test.jsx
packages/dx-react-grid-material-ui/src/templates/table-edit-cell.jsx
packages/dx-react-grid-material-ui/src/templates/table-edit-cell.test.jsx
packages/dx-react-grid-material-ui/src/templates/table-header-cell.jsx
packages/dx-react-grid/docs/reference/table.md

Created a pull request for issue #791
Would you please consider it?

feat(react-grid): support center alignment for columns

---

packages/dx-grid-core/src/plugins/table-column-resizing/computeds.js
packages/dx-grid-core/src/plugins/table-column-resizing/computeds.test.js
packages/dx-grid-core/src/utils/table.js
packages/dx-grid-core/src/utils/table.test.js
packages/dx-react-grid/src/plugins/table-column-resizing.jsx
packages/dx-react-grid/src/plugins/table-column-resizing.test.jsx

perf(react-grid): optimize column resizing

---

scripts/ts-generator.js

fix(react-grid): correct types for components

---

packages/dx-react-grid/docs/reference/custom-grouping.md

fix(react-grid): fix incorrect prop types for CustomGrouping

---

packages/dx-react-grid/docs/reference/table-column-resizing.md

fix(react-grid): fix ts for TableColumnResizing

---

packages/dx-react-grid/src/plugins/table-selection.jsx
packages/dx-react-grid/src/plugins/table-selection.test.jsx

fix(react-grid): fix the 'selectByRowClick' prop processing

---

packages/dx-react-demos/src/demo-sources/grid-featured-redux-integration/bootstrap3/demo.jsx
packages/dx-react-demos/src/demo-sources/grid-featured-redux-integration/bootstrap4/demo.jsx
packages/dx-react-demos/src/demo-sources/grid-featured-redux-integration/material-ui/demo.jsx

Summary:
- `demo.jsxt` file was splitted up by themes. 
- `withStyles` is removed from bs3/4 demos.

chore(react-grid-demos): fix the 'Redux Integration' demo

---

packages/dx-react-grid/docs/reference/integrated-filtering.md

fix(react-grid): correct filtering predicate type

---

packages/dx-react-chart-bootstrap4/src/templates/axis/line.jsx
packages/dx-react-chart-bootstrap4/src/templates/axis/line.test.jsx
packages/dx-react-chart-bootstrap4/src/templates/axis/tick.jsx
packages/dx-react-chart-bootstrap4/src/templates/axis/tick.test.jsx
packages/dx-react-chart-bootstrap4/src/templates/grid/line.jsx
packages/dx-react-chart-bootstrap4/src/templates/grid/line.test.jsx
packages/dx-react-chart-material-ui/src/templates/axis/line.jsx
packages/dx-react-chart-material-ui/src/templates/axis/line.test.jsx
packages/dx-react-chart-material-ui/src/templates/axis/tick.jsx
packages/dx-react-chart-material-ui/src/templates/axis/tick.test.jsx
packages/dx-react-chart-material-ui/src/templates/grid/line.jsx
packages/dx-react-chart-material-ui/src/templates/grid/line.test.jsx

Fix hidden line in bootstrap4 theme

chore(react-chart): fix hidden line

---

packages/dx-react-grid-bootstrap3/src/plugins/virtual-table.jsx
packages/dx-react-grid-bootstrap3/src/templates/layout.jsx
packages/dx-react-grid-bootstrap3/src/templates/paging-panel/pager.jsx
packages/dx-react-grid-bootstrap3/src/templates/table-container.jsx
packages/dx-react-grid-bootstrap3/src/templates/table-header-cell.jsx
packages/dx-react-grid-bootstrap3/src/templates/toolbar/toolbar.jsx
packages/dx-react-grid-bootstrap4/src/plugins/virtual-table.jsx
packages/dx-react-grid-bootstrap4/src/templates/layout.jsx
packages/dx-react-grid-bootstrap4/src/templates/layout.test.jsx
packages/dx-react-grid-bootstrap4/src/templates/paging-panel/pager.jsx
packages/dx-react-grid-demos/src/demo-sources/grid-virtual-scrolling/stretching-to-parent-element.jsxt
packages/dx-react-grid-material-ui/src/plugins/virtual-table.jsx
packages/dx-react-grid-material-ui/src/templates/layout.jsx
packages/dx-react-grid-material-ui/src/templates/paging-panel/pager.jsx
packages/dx-react-grid-material-ui/src/templates/toolbar/toolbar.jsx
packages/dx-react-grid/docs/guides/virtual-scrolling.md
packages/dx-react-grid/docs/reference/virtual-table.md
packages/dx-react-grid/src/components/table-layout/virtual-table-layout.jsx
packages/dx-react-grid/src/components/table-layout/virtual-table-layout.test.jsx
packages/dx-react-grid/src/grid.jsx
packages/dx-react-grid/src/grid.test.jsx
packages/dx-react-grid/src/plugins/grid-core.jsx
packages/dx-react-grid/src/plugins/grid-core.test.jsx
packages/dx-styles/dx-grid-bs4.css

feat(react-grid): support stretching virtual table to parent element

---

packages/dx-grid-core/src/plugins/filtering-state/reducers.js
packages/dx-grid-core/src/plugins/filtering-state/reducers.test.js

fix(grid-core): fix incorrect filter updating

---

packages/dx-react-grid-material-ui/src/templates/table-header-cell/sorting-control.jsx
packages/dx-styles/dx-grid-bs4.css

fix(react-grid): fix word wrap behavior with the SortingControl

---

site/_layouts/default.html
site/_layouts/docs.html
site/css/site.css

Related search config: https://github.com/algolia/docsearch-configs/blob/master/configs/devextreme_reactive.json

chore: add site search

---

packages/dx-react-grid/docs/reference/custom-summary.md
packages/dx-react-grid/docs/reference/integrated-summary.md

fix(react-grid): add missed optionals to docs

---

packages/dx-grid-core/src/plugins/integrated-grouping/computeds.js
packages/dx-grid-core/src/plugins/integrated-grouping/computeds.test.js

fix(grid): fix group row level key calculation

---

packages/dx-react-grid/docs/reference/paging-panel.md
packages/dx-vue-grid/docs/reference/paging-panel.md

fix(grid): add missed props to documentation

---

packages/dx-grid-core/src/utils/virtual-table.js
packages/dx-grid-core/src/utils/virtual-table.test.js
packages/dx-react-grid/src/components/table-layout/__snapshots__/virtual-table-layout.test.jsx.snap

fix(react-grid): fix virtual table layout in Edge

---

packages/dx-react-core/src/sizer.jsx
packages/dx-react-grid-bootstrap3/src/templates/layout.jsx
packages/dx-react-grid-bootstrap3/src/templates/table-no-data-cell.jsx
packages/dx-react-grid-bootstrap3/src/templates/table-no-data-cell.test.jsx
packages/dx-react-grid-bootstrap4/src/templates/layout.jsx
packages/dx-react-grid-bootstrap4/src/templates/table-no-data-cell.jsx
packages/dx-react-grid-bootstrap4/src/templates/table-no-data-cell.test.jsx
packages/dx-react-grid-material-ui/src/templates/layout.jsx
packages/dx-react-grid-material-ui/src/templates/table-no-data-cell.jsx
packages/dx-react-grid-material-ui/src/templates/table-no-data-cell.test.jsx
packages/dx-styles/dx-grid-bs4.css

fix(react-grid): fix the 'no data' message alignment

---

packages/dx-chart-core/src/utils/event-tracker.js
packages/dx-chart-core/src/utils/event-tracker.test.js
packages/dx-chart-core/src/utils/hover-state.js
packages/dx-chart-core/src/utils/hover-state.test.js
packages/dx-chart-core/src/utils/series.js
packages/dx-chart-core/src/utils/series.test.js

All valid series points (not the first one only) are passed to tracker event handlers.
Hover target is selected based on *distance* from pointer location to candidate.

chore(react-chart): fix close points hit testing

---

packages/dx-react-chart-demos/src/demo-sources/bar-chart/bootstrap4/series-interaction.jsx
packages/dx-react-chart-demos/src/demo-sources/bar-chart/material-ui/series-interaction.jsx
packages/dx-react-chart-demos/src/demo-sources/chart-basic/bar-line.jsxt
packages/dx-react-chart-demos/src/demo-sources/chart-featured-customize-components/demo.jsxt
packages/dx-react-chart-demos/src/demo-sources/interaction/multiple-selection.jsxt
packages/dx-react-chart-demos/src/demo-sources/interaction/selection.jsxt
packages/dx-react-chart-demos/src/demo-sources/interaction/single-multiple-selection.jsxt
packages/dx-react-chart/demos/overview/multiple-axes.md
packages/dx-react-chart/docs/guides/hover-and-selection.md
packages/dx-react-grid-demos/package.json
packages/dx-react-grid-demos/src/demo-sources/grid-featured-chart-integration/bootstrap4/demo.jsx
packages/dx-react-grid-demos/src/demo-sources/grid-featured-chart-integration/material-ui/demo.jsx

Fixes several typos occurred after several merges in a previous PR.

chore(react-chart): fix several typos

---

packages/dx-chart-core/src/utils/legend.js
packages/dx-chart-core/src/utils/legend.test.js

Fixes https://github.com/DevExpress/devextreme-reactive/issues/1717.

fix(react-chart): fix-pie-legend

---

packages/dx-react-grid-bootstrap3/src/templates/table-tree-cell.jsx
packages/dx-react-grid-bootstrap3/src/templates/table-tree-cell.test.jsx
packages/dx-react-grid-bootstrap3/src/templates/table-tree-content.jsx
packages/dx-react-grid-bootstrap4/src/templates/table-tree-cell.jsx
packages/dx-react-grid-bootstrap4/src/templates/table-tree-cell.test.jsx
packages/dx-react-grid-bootstrap4/src/templates/table-tree-content.jsx
packages/dx-react-grid-material-ui/src/templates/table-tree-cell.jsx
packages/dx-react-grid-material-ui/src/templates/table-tree-cell.test.jsx
packages/dx-react-grid-material-ui/src/templates/table-tree-content.jsx

fix(react-grid): apply wordWrapEnabled property to TableTreeColumn

---

packages/dx-react-chart-bootstrap4/package.json

fix(react-chart-bootstrap4): fix dependencies section

---

packages/dx-react-core/src/sizer.tsx
packages/dx-react-grid-bootstrap3/src/templates/layout.jsx
packages/dx-react-grid-bootstrap3/src/templates/table-no-data-cell.jsx
packages/dx-react-grid-bootstrap3/src/templates/table-no-data-cell.test.jsx
packages/dx-react-grid-bootstrap4/src/templates/layout.jsx
packages/dx-react-grid-bootstrap4/src/templates/table-no-data-cell.jsx
packages/dx-react-grid-bootstrap4/src/templates/table-no-data-cell.test.jsx
packages/dx-react-grid-material-ui/src/templates/layout.jsx
packages/dx-react-grid-material-ui/src/templates/table-no-data-cell.jsx
packages/dx-react-grid-material-ui/src/templates/table-no-data-cell.test.jsx
packages/dx-styles/dx-grid-bs4.css

fix(react-core): notify Sizer content when container size is increasing

---

packages/dx-chart-core/src/plugins/series/computeds.test.ts
packages/dx-chart-core/src/plugins/series/computeds.ts
packages/dx-react-chart-demos/src/demo-sources/tooltip/test-not-crash.jsxt

Fixes https://github.com/DevExpress/devextreme-reactive/issues/1845.

fix(react-chart): fix line target element getter

---

packages/dx-react-core/api/dx-react-core.api.ts
packages/dx-react-core/src/plugin-based/plugin.tsx
packages/dx-react-core/src/types.ts

fix(react-core): correct IDependency definition

---

scripts/publish-npm.js

[--npm-tag -> --dist-tag](https://github.com/lerna/lerna/blob/master/commands/publish/CHANGELOG.md#bug-fixes-6)

chore: fix publishing script

---

packages/dx-react-grid-bootstrap3/src/templates/paging-panel/pagination.jsx
packages/dx-react-grid-bootstrap3/src/templates/paging-panel/pagination.test.jsx
packages/dx-react-grid-bootstrap4/src/templates/paging-panel/pagination.test.jsx
packages/dx-react-grid-material-ui/src/templates/paging-panel/pagination.jsx
packages/dx-react-grid-material-ui/src/templates/paging-panel/pagination.test.jsx

feat(react-grid): add aria-labels for pager buttons

---

packages/dx-chart-core/src/types/plugins.animation.types.ts
packages/dx-react-chart/api/dx-react-chart.api.ts
packages/dx-react-chart/src/types/plugins.hover-state.types.ts
packages/dx-react-chart/src/types/plugins.viewport.types.ts

Fixes https://github.com/DevExpress/devextreme-reactive/issues/1923.

fix(react-chart): fix generated dts

---

packages/dx-react-grid-bootstrap3/src/templates/table-fixed-cell.jsx
packages/dx-react-grid-bootstrap3/src/templates/table-fixed-cell.test.jsx
packages/dx-react-grid-bootstrap4/src/templates/table-fixed-cell.jsx
packages/dx-react-grid-bootstrap4/src/templates/table-fixed-cell.test.jsx
packages/dx-react-grid-bootstrap4/src/templates/table-select-row.jsx
packages/dx-react-grid-bootstrap4/src/templates/table-select-row.test.jsx
packages/dx-react-grid-material-ui/src/templates/table-fixed-cell.jsx
packages/dx-react-grid-material-ui/src/templates/table-fixed-cell.test.jsx
packages/dx-react-grid-material-ui/src/templates/table-select-row.jsx
packages/dx-react-grid-material-ui/src/templates/table-select-row.test.jsx
packages/dx-react-grid-material-ui/src/utils/get-selection-color.jsx
packages/dx-react-grid/src/plugins/table-fixed-columns.tsx
packages/dx-react-grid/src/types/column-operations/table-fixed-columns.types.ts
packages/dx-styles/dx-grid-bs4.scss

fix(react-grid): Fixed column cell of selected row is not highlighted

---

packages/dx-react-scheduler-demos/src/demo-sources/scheduler-localization/material-ui/locale.jsx

I use dx [localization files](https://github.com/DevExpress/DevExtreme/tree/19_1/js/localization/messages).

chore(react-scheduler-demos): change localization messages

---

packages/dx-grid-core/src/plugins/virtual-table-state/helpers.test.ts
packages/dx-grid-core/src/plugins/virtual-table-state/helpers.ts

fix(react-grid): change processing of last page in lazy load mode

---

packages/dx-grid-core/src/plugins/table-selection/helpers.ts
packages/dx-react-grid/src/plugins/table-fixed-columns.test.tsx
packages/dx-react-grid/src/plugins/table-fixed-columns.tsx
packages/dx-react-grid/src/plugins/table-selection.test.tsx
packages/dx-react-grid/src/plugins/table-selection.tsx

fix(react-grid): use default color for selected fixed cell if highlight is disabled

---

.github/lock.yml
.github/no-response.yml

The previous name was not clear.

chore: change the waiting label name

---

packages/dx-react-chart/src/plugins/zoom-and-pan.test.tsx
packages/dx-react-chart/src/plugins/zoom-and-pan.tsx

Fixes https://github.com/DevExpress/devextreme-reactive/issues/2121.

fix(react-chart): fix zooming on IPad

---

packages/dx-core/src/types.ts
packages/dx-react-core/api/dx-react-core.api.md
packages/dx-react-core/src/types.ts

fix(react-core): get rid of redundant type

---

packages/dx-react-chart-material-ui/src/templates/layout.jsx

fix(react-chart-material-ui): apply correct layout height

---

packages/dx-chart-core/src/utils/scale.test.ts
packages/dx-chart-core/src/utils/scale.ts

Fixes https://github.com/DevExpress/devextreme-reactive/issues/2171.

fix(react-chart): fix zooming over minimal threshold

---

packages/dx-react-scheduler-material-ui/src/templates/drag-drop/appointments.jsx
packages/dx-react-scheduler/src/plugins/drag-drop-provider.tsx

fix(react-scheduler-material-ui): remove transparent border from draft appointment

---

packages/dx-react-grid/src/utils/row-cache.test.ts
packages/dx-react-grid/src/utils/row-cache.ts

fix(react-grid): allow retrieving the incomplete pages from cache

---

packages/dx-react-scheduler-demos/src/demo-sources/scheduler-editing/material-ui/drag-drop.jsx
packages/dx-scheduler-core/src/utils.test.ts
packages/dx-scheduler-core/src/utils.ts

fix(react-scheduler): prevent double render of all-day recurrence appointments

---

packages/dx-grid-core/src/plugins/virtual-table/helpers.test.ts
packages/dx-grid-core/src/plugins/virtual-table/helpers.ts
packages/dx-grid-core/src/types/virtual-table.types.ts
packages/dx-grid-core/src/utils/virtual-table.test.ts
packages/dx-grid-core/src/utils/virtual-table.ts
packages/dx-react-grid-demos/src/demo-sources/grid-grouping/remote-grouping-with-local-expanding.jsxt
packages/dx-react-grid/src/components/table-layout/virtual-table-layout.test.tsx
packages/dx-react-grid/src/components/table-layout/virtual-table-layout.tsx
packages/dx-react-grid/src/plugins/virtual-table/virtual-table.tsx

fix(react-grid): correctly handle column count changes in virtual table

---

packages/dx-react-scheduler/src/plugins/all-day-panel.test.tsx
packages/dx-react-scheduler/src/plugins/all-day-panel.tsx
packages/dx-scheduler-core/src/plugins/all-day-panel/computeds.ts

fix(react-scheduler): fix incorrect render of recurrent appointments in the first cell of AllDayPanel

---

packages/dx-react-scheduler/src/plugins/editing-state.test.tsx
packages/dx-react-scheduler/src/plugins/editing-state.tsx

fix(react-scheduler): fix create an appointment on the first call of AppointmentForm

---

packages/dx-react-grid-material-ui/src/templates/paging-panel/page-size-selector.jsx
packages/dx-react-grid-material-ui/src/templates/paging-panel/page-size-selector.test.jsx

fix(react-grid): correct displaying Page Size Selector in Edge

---

packages/dx-react-scheduler-demos/src/demo-sources/scheduler-featured-editing/material-ui/demo.jsx
packages/dx-react-scheduler/src/plugins/drag-drop-provider.test.tsx
packages/dx-react-scheduler/src/plugins/drag-drop-provider.tsx

fix(react-scheduler): make it possible to drag-drop appointments in MonthView with AllDayPanel plugin

---

packages/dx-react-grid-demos/src/demo-sources/grid-lazy-loading/infinite-scrolling.jsxt
packages/dx-react-grid-demos/src/demo-sources/grid-lazy-loading/remote-data-basic.jsxt

chore(react-grid-demos): switch to useReducer, fix rows loading

---

packages/dx-scheduler-core/src/plugins/editing-state/helpers.test.ts
packages/dx-scheduler-core/src/plugins/editing-state/helpers.ts
packages/dx-scheduler-core/src/utils.test.ts
packages/dx-scheduler-core/src/utils.ts

fix(scheduler-core): fix recurrent appointment disappearing after dragdrop

---

packages/dx-chart-core/src/types/chart-core.types.ts
packages/dx-chart-core/src/utils/scale.ts
packages/dx-react-chart/api/dx-react-chart.api.md

fix(react-chart): fix typescript in scales

---

packages/dx-react-scheduler-material-ui/src/templates/edit-recurrence-menu/layout.jsx
packages/dx-react-scheduler/src/plugins/edit-recurrence-menu.test.tsx
packages/dx-react-scheduler/src/plugins/edit-recurrence-menu.tsx

fix(react-scheduler): make it possible to create an appointment after cancelled drag-drop

---

packages/dx-react-grid-material-ui/src/templates/filter-row/filter-selector.jsx
packages/dx-react-grid-material-ui/src/templates/filter-row/filter-selector.test.jsx

fix(react-grid): correct displaying Filter Selector in Edge

---

packages/dx-react-scheduler-demos/src/demo-sources/scheduler-editing/material-ui/controlled.jsx
packages/dx-react-scheduler-demos/src/demo-sources/scheduler-editing/material-ui/delete-confirmation.jsx
packages/dx-react-scheduler-demos/src/demo-sources/scheduler-editing/material-ui/uncontrolled.jsx

fix(react-scheduler-demos): add capability to delete zero index appointment

---

packages/dx-grid-core/src/plugins/table-header-row/helpers.test.ts
packages/dx-grid-core/src/plugins/table-header-row/helpers.ts
packages/dx-grid-core/src/types/header-row.types.ts

fix(react-grid): add type checking for next column in getNextColumnName

---

packages/dx-grid-core/src/types/editing.types.ts
packages/dx-react-grid/api/dx-react-grid.api.md
packages/dx-react-grid/src/types/editing/editing-state.types.ts
packages/dx-react-grid/src/types/index.ts

fix(react-grid): correctly import interface from grid-core package

---

packages/dx-grid-core/src/plugins/table-header-row/helpers.test.ts
packages/dx-grid-core/src/plugins/table-header-row/helpers.ts
packages/dx-grid-core/src/types/header-row.types.ts
packages/dx-react-grid/api/dx-react-grid.api.md
packages/dx-react-grid/src/plugins/table-header-row.test.tsx
packages/dx-react-grid/src/plugins/table-header-row.tsx

fix(react-grid): check next column name by column.name instead type

---

packages/dx-scheduler-core/src/plugins/common/computeds.test.ts
packages/dx-scheduler-core/src/plugins/common/computeds.ts
packages/dx-scheduler-core/src/plugins/common/helpers.test.ts
packages/dx-scheduler-core/src/plugins/common/helpers.ts

fix(scheduler-core): calculate the last TimeScale EndDate correctly

---

renovate.json

chore: fix renovate packagePatterns config

---

packages/dx-grid-core/src/index.ts
packages/dx-grid-core/src/plugins/table-inline-cell-editing/computeds.test.ts
packages/dx-grid-core/src/plugins/table-inline-cell-editing/computeds.ts
packages/dx-grid-core/src/plugins/table-inline-cell-editing/helpers.ts
packages/dx-grid-core/src/types/editing.types.ts
packages/dx-react-grid/src/plugins/table-inline-cell-editing.test.tsx
packages/dx-react-grid/src/plugins/table-inline-cell-editing.tsx

fix(react-grid): rerender only cell being edited in inline cell editing mode

---

packages/dx-react-grid-demos/src/demo-sources/grid-filtering/material-ui/advanced-filter-row.jsx

fix(react-grid-demos): add margin for custom numeric input

---

packages/dx-react-scheduler-material-ui/src/templates/views/vertical/day-scale/cell.jsx

fix(react-scheduler-material-ui): Fix DayView DayScale cell

---

packages/dx-react-grid-bootstrap3/src/templates/layout.jsx
packages/dx-react-grid-bootstrap3/src/templates/layout.test.jsx

fix(react-grid-bootstrap3): correct sticky header color

---

packages/dx-demo-shell/src/demo-viewer/demo-frame.jsx

fix(demo-shell): re-render demo frame on submitting custom theme link

---

packages/dx-react-grid-bootstrap3/src/templates/table-edit-cell.test.jsx
packages/dx-react-grid-bootstrap4/src/templates/table-edit-cell.test.jsx
packages/dx-react-grid-material-ui/src/templates/table-edit-cell.jsx
packages/dx-react-grid-material-ui/src/templates/table-edit-cell.test.jsx

fix(react-grid-material-ui): show zero numbers in editors

---

packages/dx-grid-core/src/types/filtering.types.ts
packages/dx-react-grid/docs/reference/filtering-state.md

docs(react-grid): fix typographical error in 'FilteringState' doc

---

.circleci/config.yml
package.json

Please, update your `yarn` version to `1.21.1`.
@ushkal, @MaximKudriavtsev, @LazyLahtak, @Krijovnick

chore: update yarn version

---

packages/dx-react-grid/docs/reference/table-fixed-columns.md
packages/dx-react-grid/src/plugins/table-fixed-columns.tsx

related to https://github.com/DevExpress/devextreme-reactive/issues/2607#issuecomment-567843925

fix(react-grid): specify detail row as a dependency for fixed columns

---

babel.config.js
packages/dx-react-chart-bootstrap4/package.json
packages/dx-react-chart-material-ui/package.json
packages/dx-react-grid-bootstrap3/package.json
packages/dx-react-grid-bootstrap4/package.json
packages/dx-react-grid-material-ui/package.json
packages/dx-react-scheduler-material-ui/package.json
yarn.lock

Add Nullish Coalescing Operator:
```js
const result = value ?? defaultValue
```
equal
```js
let result;
if (value !== null && value !== undefined) {
result = value;
} else {
result = defaultValue;
}
```
_________________________
Add Optional Chaining:
```js
const obj = {
field: {
value: 5,
},
}
obj?.field?.value     // 5
obj?.subfield?.value  //undefined
```
```js
const obj = {
func: () => { return 'someText'; },
}
obj?.func?.()         // 'someText'
obj?.anotherFunc?.()  // undefined
```

chore: add ES2020 features using babel's plugins

---

packages/dx-react-scheduler-material-ui/src/templates/edit-recurrence-menu/layout.jsx
packages/dx-react-scheduler-material-ui/src/templates/edit-recurrence-menu/layout.test.jsx
packages/dx-react-scheduler/api/dx-react-scheduler.api.md
packages/dx-react-scheduler/docs/reference/appointment-form.md
packages/dx-react-scheduler/src/plugins/appointment-form.tsx
packages/dx-react-scheduler/src/plugins/edit-recurrence-menu.tsx
packages/dx-react-scheduler/src/types/editing/appointment-form.types.ts

fix(react-scheduler): fix localization messages in Scheduler

---

packages/dx-react-scheduler/src/plugins/appointments.test.tsx
packages/dx-react-scheduler/src/plugins/appointments.tsx
packages/dx-scheduler-core/src/index.ts
packages/dx-scheduler-core/src/plugins/appointments/helpers.test.ts
packages/dx-scheduler-core/src/plugins/appointments/helpers.ts

fix(react-scheduler): fix error caused by view switching when all-day panel is used

---

package.json

With this pr, generated api.md files are updated automatically

chore: copy api file when update-api is running locally

---

packages/dx-react-scheduler-material-ui/src/templates/utils.js
packages/dx-react-scheduler-material-ui/src/templates/utils.test.js
packages/dx-scheduler-core/src/plugins/resources/helpers.test.ts
packages/dx-scheduler-core/src/plugins/resources/helpers.ts

fix(react-scheduler): use defaults when resource id is not specified in instances but is specified in an appointment

---

packages/dx-react-grid/src/plugins/table-group-row.test.tsx
packages/dx-react-grid/src/plugins/table-group-row.tsx

fix(react-grid): render stub cell on group row and flex column intersection

---

packages/dx-react-core/src/utils/state-helper.ts

fix(react-core): notify state update outside the state updater

---

packages/dx-grid-core/src/plugins/virtual-table/helpers.test.ts
packages/dx-grid-core/src/plugins/virtual-table/helpers.ts
packages/dx-grid-core/src/types/virtual-table.types.ts
packages/dx-react-grid/api/dx-react-grid.api.md
packages/dx-react-grid/src/plugins/virtual-table/virtual-table.test.tsx
packages/dx-react-grid/src/plugins/virtual-table/virtual-table.tsx
packages/dx-react-grid/src/types/tables/virtual-table.types.ts

fix(react-grid): make 'onTopRowChange' work with detail row

---

packages/dx-react-grid-export/api/dx-react-grid-export.api.md
packages/dx-react-grid-export/src/index.ts
packages/dx-react-grid-export/src/types/export/exporter.types.ts

fix(react-grid): add GridExporter to ts definition

---

packages/dx-site/src/components/cookie.module.scss

chore: make cookies visible over code

---

packages/dx-grid-core/src/plugins/virtual-table/helpers.test.ts
packages/dx-grid-core/src/plugins/virtual-table/helpers.ts

fix(react-grid): check viewport position when handle top row id

---

packages/dx-react-grid/src/components/table-layout/virtual-table-layout.test.tsx
packages/dx-react-grid/src/components/table-layout/virtual-table-layout.tsx

fix(react-grid): make possible put VirtualTable in container with scale

---

packages/dx-site/gatsby-config.js

chore: fix typo in the site page title

---

packages/dx-react-grid-material-ui/src/templates/constants.js
packages/dx-react-grid-material-ui/src/templates/paging-panel/page-size-selector.jsx

fix(react-grid-material-ui): apply page size selector position only for Edge

---

packages/dx-react-grid/src/plugins/virtual-table/virtual-table-state.test.tsx
packages/dx-react-grid/src/plugins/virtual-table/virtual-table-state.tsx

fix(react-grid): fix typo in action name

---

packages/dx-react-core/src/plugin-based/plugin.test.tsx
packages/dx-react-core/src/plugin-based/plugin.tsx
packages/dx-react-scheduler/src/plugins/resources.test.tsx

fix(react-core): check dependencies on plugin mount

---

packages/dx-grid-core/src/plugins/virtual-table-state/computeds.ts
packages/dx-grid-core/src/types/virtual-table-state.types.ts
packages/dx-react-grid/src/plugins/virtual-table/virtual-table-state.test.tsx
packages/dx-react-grid/src/plugins/virtual-table/virtual-table-state.tsx

fix(react-grid): calculate actual row count in VirtualTableState

---

packages/dx-react-grid/src/plugins/virtual-table/virtual-table-state.test.tsx
packages/dx-react-grid/src/plugins/virtual-table/virtual-table-state.tsx

fix(react-grid): provide right 'skip' value on filtering

---

packages/dx-grid-core/src/plugins/table-group-row/computeds.test.ts
packages/dx-grid-core/src/plugins/table-group-row/computeds.ts

fix(react-grid): calculate group row colspan correct

---

packages/dx-react-grid-demos/src/demo-sources/grid-export/supported-grid-features.jsxt

Add additional selection in [Supported Grid Features](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/export/#supported-grid-features) demo to make exported file more evident.

chore(react-grid-demos): Add additional selection in export demo

---

packages/dx-react-grid/docs/reference/grid-exporter.md

docs(react-grid): correct GridExporter plugin's import

---

packages/dx-react-core/src/draggable.tsx

fix(react-core): make scrolling behavior similar in Safari and Chrome while drag columns

---

packages/dx-react-scheduler-material-ui/src/templates/appointment-form/recurrence/layout.jsx
packages/dx-react-scheduler-material-ui/src/templates/appointment-form/recurrence/layout.test.jsx

fix(react-scheduler): fix mui warning in recurrence layout

---

packages/dx-scheduler-core/package.json
yarn.lock

fix(scheduler-core): update rrule version to 2.6.4 and fix it

---

packages/dx-chart-core/package.json
packages/dx-chart-core/src/utils/event-tracker.test.ts
packages/dx-chart-core/src/utils/event-tracker.ts
packages/dx-core/src/index.ts
packages/dx-core/src/utils.ts

fix(chart-core): add handler only when window exists

---

packages/dx-core/src/plugin-host.test.ts
packages/dx-core/src/plugin-host.ts

Fix #3095, improve plugin-host collect and get methods to improve rendering performance

perf(core): improve rendering performance (#3095)

---

packages/dx-grid-core/src/plugins/virtual-table-state/helpers.test.ts
packages/dx-grid-core/src/plugins/virtual-table-state/helpers.ts

fix(react-grid): correct row interval request with infinite scrolling

---

packages/dx-react-grid/api/dx-react-grid.api.md
packages/dx-react-grid/docs/reference/data-type-provider.md
packages/dx-react-grid/src/types/data-type-provider/data-type-provider.types.ts

fix(react-grid): correct DataTypeProvider.ValueEditorProps types

---

packages/dx-react-scheduler-material-ui/api/dx-react-scheduler-material-ui.api.md
packages/dx-react-scheduler/docs/reference/day-view.md
packages/dx-react-scheduler/docs/reference/month-view.md
packages/dx-react-scheduler/docs/reference/week-view.md
packages/dx-react-scheduler/src/plugins/basic-view.test.tsx
packages/dx-react-scheduler/src/types/views/base-view.types.ts
packages/dx-react-scheduler/src/types/views/basic-view.types.ts
packages/dx-react-scheduler/src/types/views/day-view.types.ts
packages/dx-react-scheduler/src/types/views/month-view.types.ts
packages/dx-react-scheduler/src/types/views/vertical-view.types.ts
packages/dx-react-scheduler/src/types/views/week-view.types.ts
packages/dx-scheduler-core/src/plugins/drag-drop-provider/helpers.test.ts

docs(react-scheduler): fix components' description in Views' API reference

---

packages/dx-grid-core/src/plugins/custom-grouping/computeds.ts
packages/dx-grid-core/src/plugins/custom-grouping/helpers.ts
packages/dx-grid-core/src/plugins/integrated-grouping/computeds.ts
packages/dx-grid-core/src/plugins/integrated-grouping/helpers.ts
packages/dx-grid-core/src/types/grouping.types.ts
packages/dx-react-grid-demos/src/demo-sources/grid-grouping/max-call-stack-test.jsxt

fix(react-grid): make grouping work with a high level of nested groups

---

packages/dx-react-scheduler/src/plugins/day-view.test.tsx
packages/dx-react-scheduler/src/plugins/day-view.tsx
packages/dx-react-scheduler/src/plugins/integrated-grouping.test.tsx
packages/dx-react-scheduler/src/plugins/integrated-grouping.tsx
packages/dx-react-scheduler/src/plugins/week-view.test.tsx
packages/dx-react-scheduler/src/plugins/week-view.tsx
packages/dx-scheduler-core/src/plugins/common/computeds.test.ts
packages/dx-scheduler-core/src/plugins/common/computeds.ts
packages/dx-scheduler-core/src/plugins/common/helpers.test.ts
packages/dx-scheduler-core/src/plugins/common/helpers.ts
packages/dx-scheduler-core/src/plugins/integrated-grouping/computeds.test.ts
packages/dx-scheduler-core/src/plugins/integrated-grouping/computeds.ts

fix(react-scheduler): display time in Time Scale correctly when a DST change is present

---

packages/dx-site/src/components/docs/survey-header-addon.jsx
packages/dx-site/src/components/docs/survey-header-addon.module.scss
packages/dx-site/src/components/layouts/page-layout.jsx

chore(site): add a survey banner

---

packages/dx-site/src/pages/docs.jsx

chore(site): move topic about plugin system into "advanced" section

---

packages/dx-chart-core/src/plugins/controller-component/computeds.test.ts
packages/dx-chart-core/src/plugins/controller-component/computeds.ts

fix(react-chart): fix series showing if the `scaleName` contains `top`/`bottom`

---

packages/dx-chart-core/src/constants.ts
packages/dx-chart-core/src/plugins/controller-component/computeds.test.ts
packages/dx-chart-core/src/plugins/controller-component/computeds.ts

fix(react-chart): fix chart display for zoom factor 90%

---

packages/dx-react-scheduler-demos/src/demo-sources/test/test-ts.tsx
packages/dx-react-scheduler-material-ui/api/dx-react-scheduler-material-ui.api.md
packages/dx-react-scheduler/docs/reference/confirmation-dialog.md

fix(react-scheduler): use correct type for ConfirmationDialog's messages

---

packages/dx-react-scheduler-material-ui/src/templates/common/container.jsx

fix(react-scheduler): fix container classes

---

packages/dx-grid-core/src/utils/table.test.ts
packages/dx-grid-core/src/utils/table.ts

fix(react-grid): fix page freezes on drag and drop

---

packages/dx-grid-core/src/utils/virtual-table.test.ts
packages/dx-grid-core/src/utils/virtual-table.ts

fix(react-grid): fix calculating colSpan for virtualTable

---

packages/dx-grid-core/src/utils/virtual-table.test.ts
packages/dx-grid-core/src/utils/virtual-table.ts

fix(react-grid): fix render of group cell of second level

---

packages/dx-react-scheduler/docs/reference/editing-state.md

fix(react-scheduler): Actualize types for EditingState

---

packages/dx-grid-core/src/types/filtering.types.ts
packages/dx-react-grid/api/dx-react-grid.api.md
packages/dx-react-grid/docs/reference/filtering-state.md

fix(react-grid): Extend type of Filter value

---

packages/dx-react-grid/api/dx-react-grid.api.md
packages/dx-react-grid/docs/reference/data-type-provider.md
packages/dx-react-grid/src/types/data-type-provider/data-type-provider.types.ts

fix(react-grid): Fix type DataTypeProvider.ValueEditorProps

---

packages/dx-react-scheduler/api/dx-react-scheduler.api.md
packages/dx-react-scheduler/docs/reference/appointment-form.md
packages/dx-react-scheduler/src/types/editing/appointment-form.types.ts

fix(react-scheduler): Rename field in WeeklyRecurrenceSelectorProps

---

packages/dx-core/merge-dts.js
packages/dx-core/package.json
packages/dx-core/src/index.ts
packages/dx-core/src/types.ts
packages/dx-core/tsconfig.dts.json
packages/dx-grid-core/src/plugins/sorting-state/helpers.ts
packages/dx-react-core/api/dx-react-core.api.md
packages/dx-react-core/src/plugin-based/plugin.tsx
packages/dx-react-core/src/types.ts
packages/dx-react-grid/api/dx-react-grid.api.md
packages/dx-react-grid/src/types/grouping/group-row.types.ts
packages/dx-react-grid/src/types/index.ts
packages/dx-react-grid/src/types/summary/table-summary-row.types.ts
packages/dx-site/package.json
yarn.lock

https://supportcenter.devexpress.com/internal/ticket/details/T1047971

fix(core): Make dx-core type public for fix lib check react-grid compilation error

---

packages/dx-grid-core/src/types/virtual-table.types.ts
packages/dx-grid-core/src/utils/virtual-table.ts
packages/dx-react-grid/src/components/table-layout/virtual-table-layout.test.tsx

fix(react-grid): fix column resizing for VirtualTable (T1106563)

---

packages/dx-react-grid/src/components/table-layout/__snapshots__/virtual-table-layout.test.tsx.snap
packages/dx-react-grid/src/components/table-layout/virtual-table-layout-block.tsx
packages/dx-react-grid/src/components/table-layout/virtual-table-layout.test.tsx
packages/dx-react-grid/src/components/table-layout/virtual-table-layout.tsx
packages/dx-react-grid/src/types/layout/table-layout.types.ts

fix(react-grid): fix flickering of virtual table (T1108194)

---

packages/dx-core/src/utils.test.ts
packages/dx-core/src/utils.ts

fix(core): fix updating plugins

---

packages/dx-react-scheduler-material-ui/src/templates/all-day-panel/cell.jsx
packages/dx-react-scheduler-material-ui/src/templates/appointment-form/basic/layout.jsx
packages/dx-react-scheduler-material-ui/src/templates/appointment-form/recurrence/layout.jsx
packages/dx-react-scheduler-material-ui/src/templates/appointment-form/recurrence/layouts/daily.jsx
packages/dx-react-scheduler-material-ui/src/templates/appointment-form/recurrence/layouts/monthly.jsx
packages/dx-react-scheduler-material-ui/src/templates/appointment-form/recurrence/layouts/weekly.jsx
packages/dx-react-scheduler-material-ui/src/templates/appointment-form/recurrence/layouts/yearly.jsx
packages/dx-react-scheduler-material-ui/src/templates/appointment-form/recurrence/radio-group/end-repeat-editor.jsx
packages/dx-react-scheduler-material-ui/src/templates/appointment-form/recurrence/radio-group/monthly-editor.jsx
packages/dx-react-scheduler-material-ui/src/templates/appointment-form/recurrence/radio-group/radio-group.jsx
packages/dx-react-scheduler-material-ui/src/templates/appointment-form/recurrence/radio-group/yealy-editor.jsx
packages/dx-react-scheduler-material-ui/src/templates/confirmation-dialog/layout.jsx
packages/dx-react-scheduler-material-ui/src/templates/views/horizontal/day-scale/cell.jsx
packages/dx-react-scheduler-material-ui/src/templates/views/horizontal/time-table/cell.jsx
packages/dx-react-scheduler-material-ui/src/templates/views/vertical/day-scale/cell.jsx
packages/dx-react-scheduler-material-ui/src/templates/views/vertical/time-scale/tick-cell.jsx
packages/dx-react-scheduler-material-ui/src/templates/views/vertical/time-table/cell.jsx

fix(react-scheduler): fix types

---

packages/dx-chart-core/package.json
packages/dx-core/package.json
packages/dx-grid-core/package.json
packages/dx-react-chart-bootstrap4/package.json
packages/dx-react-chart-material-ui/package.json
packages/dx-react-chart/package.json
packages/dx-react-core/package.json
packages/dx-react-grid-bootstrap3/package.json
packages/dx-react-grid-bootstrap4/package.json
packages/dx-react-grid-export/merge-dts.js
packages/dx-react-grid-export/package.json
packages/dx-react-grid-material-ui/package.json
packages/dx-react-grid/package.json
packages/dx-react-scheduler-material-ui/package.json
packages/dx-react-scheduler/package.json
packages/dx-scheduler-core/package.json
packages/dx-testing/package.json
scripts/merge-dts.js
scripts/ts-generator.js
scripts/utils.js

Testing with https://github.com/arethetypeswrong/arethetypeswrong.github.io, before/after:

fix: conditional type exports (T1177805)
