DevExpress/devextreme-reactive

packages/dx-react-core/src/plugged/getter.jsx
packages/dx-react-core/src/plugged/getter.test.jsx

The Watcher component is already implemented for such tasks

refactor(react-core): Remove the onChange handler from the Getter component

---

packages/dx-react-grid-bootstrap3/src/templates/group-panel-cell.jsx

Fixes cancel column grouping in FireFox

fix(react-grid): cancel column grouping in FireFox

---

packages/dx-react-demos/src/bootstrap3/detail-row/detail-row-controlled.jsx
packages/dx-react-demos/src/bootstrap3/detail-row/simple-detail-row.jsx
packages/dx-react-demos/src/bootstrap3/featured/redux-integration.jsx
packages/dx-react-demos/src/bootstrap3/redux/grid-container.jsx
packages/dx-react-demos/src/bootstrap3/virtual-scrolling/integration-with-other-plugins.jsx
packages/dx-react-grid/docs/guides/detail-row.md
packages/dx-react-grid/docs/reference/README.md
packages/dx-react-grid/docs/reference/row-detail-state.md
packages/dx-react-grid/docs/reference/table-row-detail.md
packages/dx-react-grid/src/index.js
packages/dx-react-grid/src/plugins/row-detail-state.jsx
packages/dx-react-grid/src/plugins/table-row-detail.jsx
site/_data/docs/navigation.yml

Previously, to enable the 'Detail row' feature a user had to use only the 'TableRowDetail' plugin. But, this plugin mixed up the rendering and state managing functionality. Now, there are two particular plugins. The first one is the 'RowDetailState' plugin. It's responsible for a state managing. The second one is the 'TableRowDetail' plugin. It only renders a detail row. 
The following code:
<TableRowDetail
expandedRows={expandedRows}
onExpandedRowsChange={onExpandedRowsChange}
template={({ row }) =>
<GridDetailContainer
data={row}
columns={detailColumns}
/>
}
/>
should be replaced with:
<RowDetailState 
expandedRows={expandedRows}
onExpandedRowsChange={onExpandedRowsChange}
/>
<TableRowDetail
template={({ row }) =>
<GridDetailContainer
data={row}
columns={detailColumns} …

refactor(react-grid): Split TableRowDetail into the UI & state management plugins

---

packages/dx-grid-core/src/plugins/table-group-row/computeds.js
packages/dx-react-grid-bootstrap3/src/plugins/table-group-row.jsx
packages/dx-react-grid-material-ui/src/plugins/table-group-row.jsx
packages/dx-react-grid/docs/reference/table-group-row.md
packages/dx-react-grid/src/plugins/table-group-row.jsx

The `groupColumnWidth` property of the TableGroupRow plugin has been renamed to `groupIndentColumnWidth` to avoid possible confusion of what it is responsible for.

refactor(react-grid): Rename groupColumnWidth to groupIndentColumnWidth

---

packages/dx-react-grid-bootstrap3/src/plugins/table-row-detail.jsx
packages/dx-react-grid-material-ui/src/plugins/table-row-detail.jsx
packages/dx-react-grid/docs/reference/table-row-detail.md
packages/dx-react-grid/src/plugins/table-row-detail.jsx

We renamed the `detailToggleTemplate` property of the TableRowDetail plugin to `detailToggleCellTemplate` to make it consistent with the `detailToggleCellWidth` property.

refactor(react-grid): Rename detailToggleTemplate to detailToggleCellTemplate

---

packages/dx-react-grid-bootstrap3/src/plugins/table-group-row.jsx
packages/dx-react-grid-bootstrap3/src/templates/table-group-row-cell.jsx
packages/dx-react-grid-material-ui/src/plugins/table-group-row.jsx
packages/dx-react-grid-material-ui/src/templates/table-group-row-cell.jsx
packages/dx-react-grid/docs/reference/table-group-row.md
packages/dx-react-grid/src/plugins/table-group-row.jsx

The 'groupRowCellTemplate' property of the TableGroupRow plugin has been renamed to 'groupCellTemplate'

refactor(react-grid): Rename groupRowCellTemplate to groupCellTemplate

---

packages/dx-react-grid-material-ui/package.json
packages/dx-react-grid-material-ui/rollup.config.js
tools/rollup-utils.js

UMD bundle for the `@devexpress/dx-react-grid-material-ui` package is no longer provided

chore(react-grid-material-ui): swap UMD bundle with CJS one in package entry

---

packages/dx-grid-core/src/plugins/editing-state/reducers.js
packages/dx-grid-core/src/plugins/editing-state/reducers.test.js
packages/dx-grid-core/src/plugins/table-edit-row/computeds.js
packages/dx-grid-core/src/plugins/table-edit-row/computeds.test.js

In order to improve API transparency, the most recently added row will be added to the end of the addedRows property of the EditingState plugin.

refactor(react-grid): add the most recently added row to the end

---

packages/dx-grid-core/src/plugins/paging-state/reducers.js
packages/dx-grid-core/src/plugins/paging-state/reducers.test.js
packages/dx-react-grid/docs/reference/local-paging.md
packages/dx-react-grid/docs/reference/paging-panel.md
packages/dx-react-grid/docs/reference/paging-state.md
packages/dx-react-grid/src/plugins/local-paging.jsx
packages/dx-react-grid/src/plugins/local-paging.test.jsx
packages/dx-react-grid/src/plugins/paging-panel.jsx
packages/dx-react-grid/src/plugins/paging-panel.test.jsx
packages/dx-react-grid/src/plugins/paging-state.jsx
packages/dx-react-grid/src/plugins/paging-state.test.jsx

Arguments of the `setPageSize` and `setCurrentPage` actions were simpilified. 
Now, to call these actions, a user can use `numbers` instead of `objects`. See the following code:
setPageSize(5); // instead of setPageSize({ size: 5 })
and
setCurrentPage(1); // instead of setCurrentPage({ page: 1 })

refactor(react-grid): simplify arguments of the setPageSize and setCurrentPage actions

---

packages/dx-grid-core/src/utils/table.js
packages/dx-grid-core/src/utils/table.test.js
packages/dx-react-demos/src/bootstrap3/featured-remote-data/demo.jsx
packages/dx-react-demos/src/material-ui/featured-remote-data/demo.jsx
packages/dx-react-grid-bootstrap3/src/templates/table-detail-cell.jsx
packages/dx-react-grid-bootstrap3/src/templates/table-group-row-cell.jsx
packages/dx-react-grid-bootstrap3/src/templates/table-no-data-cell.jsx
packages/dx-react-grid-bootstrap3/src/templates/virtual-table.jsx
packages/dx-react-grid-material-ui/src/templates/table-detail-cell.jsx
packages/dx-react-grid-material-ui/src/templates/table-group-row-cell.jsx
packages/dx-react-grid-material-ui/src/templates/table-no-data-cell.jsx
packages/dx-react-grid/docs/reference/table-view.md
packages/dx-react-grid/src/components/table-layout.test.jsx
packages/dx-react-grid/src/components/table-layout/row-layout.jsx
packages/dx-react-grid/src/plugins/table-view.test.jsx

The `colspan` field passed to tableNoDataCellTemplate (the TableView plugin), detailCellTemplate (the TableRowDetail plugin) and groupCellTemplate (the TableGroupRow plugin) has been renamed to `colSpan`.

refactor(react-grid): rename colspan to colSpan

---

packages/dx-react-grid-bootstrap3/src/plugins/table-view.jsx
packages/dx-react-grid-bootstrap3/src/plugins/virtual-table-view.jsx
packages/dx-react-grid-material-ui/src/plugins/table-view.jsx
packages/dx-react-grid/docs/reference/table-view.md
packages/dx-react-grid/src/plugins/table-group-row.test.jsx
packages/dx-react-grid/src/plugins/table-view.jsx
packages/dx-react-grid/src/plugins/table-view.test.jsx

The `tableTemplate` property has been renamed to `tableLayoutTemplate` to make the `TableView` plugin API more eloquent.

refactor(react-grid): rename tableTemplate to tableLayoutTemplate

---

packages/dx-grid-core/src/plugins/filtering-state/computeds.js
packages/dx-grid-core/src/plugins/filtering-state/computeds.test.js
packages/dx-grid-core/src/plugins/grouping-local/computeds.js
packages/dx-grid-core/src/plugins/grouping-local/computeds.test.js
packages/dx-grid-core/src/plugins/sorting-state/computeds.js
packages/dx-grid-core/src/plugins/sorting-state/computeds.test.js
packages/dx-react-demos/src/bootstrap3/data-accessors/custom-data-accessors-in-columns.jsx
packages/dx-react-demos/src/bootstrap3/data-accessors/custom-data-accessors.jsx
packages/dx-react-demos/src/material-ui/data-accessors/custom-data-accessors-in-columns.jsx
packages/dx-react-demos/src/material-ui/data-accessors/custom-data-accessors.jsx
packages/dx-react-grid/docs/guides/data-accessors.md
packages/dx-react-grid/docs/reference/grid.md
packages/dx-react-grid/docs/reference/local-filtering.md
packages/dx-react-grid/docs/reference/local-grouping.md
packages/dx-react-grid/docs/reference/local-sorting.md
packages/dx-react-grid/docs/reference/table-edit-row.md
packages/dx-react-grid/docs/reference/table-view.md
packages/dx-react-grid/src/grid.jsx
packages/dx-react-grid/src/grid.test.jsx
packages/dx-react-grid/src/plugins/local-filtering.jsx
packages/dx-react-grid/src/plugins/local-grouping.jsx
packages/dx-react-grid/src/plugins/local-sorting.jsx
packages/dx-react-grid/src/plugins/table-edit-row.jsx
packages/dx-react-grid/src/plugins/table-edit-row.test.jsx
packages/dx-react-grid/src/plugins/table-view.jsx
packages/dx-react-grid/src/plugins/table-view.test.jsx

The `getCellData` property of the TableView plugin and the `getCellData` field of the Column interface have been renamed to `getCellValue`.

refactor(react-grid): rename getCellData to getCellValue

---

packages/dx-grid-core/src/plugins/filtering-state/computeds.js
packages/dx-react-demos/src/bootstrap3/filtering/custom-filter-row.jsx
packages/dx-react-demos/src/material-ui/filtering/custom-filter-row.jsx
packages/dx-react-grid/docs/guides/filtering.md
packages/dx-react-grid/docs/reference/local-filtering.md
packages/dx-react-grid/src/plugins/local-filtering.jsx

The 'filterFn' property of the LocalFiltering has been renamed to 'predicate'. The argument list has been changed from `filterFn(row: Row, filter: Filter) => boolean` to  `predicate(value: any, filter: Filter, row: Row) => boolean`.

refactor(react-grid): change custom filtering function signature

---

packages/dx-grid-core/src/plugins/filtering-state/computeds.js
packages/dx-grid-core/src/plugins/filtering-state/computeds.test.js
packages/dx-react-demos/src/bootstrap3/filtering/custom-filtering-algorithm.jsx
packages/dx-react-demos/src/material-ui/filtering/custom-filtering-algorithm.jsx
packages/dx-react-grid/docs/guides/filtering.md
packages/dx-react-grid/docs/reference/local-filtering.md
packages/dx-react-grid/src/plugins/local-filtering.jsx

The `filterFn` property of the `LocalFiltering` has been renamed to `getColumnPredicate`. The argument list has been changed from `filterFn(row: Row, filter: Filter) => boolean` to  `getColumnPredicate(columnName: string) => Function`.  The returning function has the following signature `(value: any, filter, row: Row) => boolean`.

refactor(react-grid): use a custom filtering algorithm depend on column name

---

packages/dx-react-grid/src/plugins/selection-state.jsx
packages/dx-react-grid/src/plugins/selection-state.test.jsx

fix(react-grid): remove a redundant SelectionState dependency on LocalGrouping

---

packages/dx-react-demos/src/bootstrap3/column-resizing/controlled.jsx
packages/dx-react-demos/src/bootstrap3/column-resizing/uncontrolled.jsx
packages/dx-react-demos/src/bootstrap3/featured-redux-integration/demo.jsx
packages/dx-react-demos/src/material-ui/column-resizing/controlled.jsx
packages/dx-react-demos/src/material-ui/column-resizing/uncontrolled.jsx
packages/dx-react-demos/src/material-ui/featured-redux-integration/demo.jsx
packages/dx-react-grid-bootstrap3/src/index.js
packages/dx-react-grid-bootstrap3/src/plugins/table-column-resizing.jsx
packages/dx-react-grid-material-ui/src/index.js
packages/dx-react-grid-material-ui/src/plugins/table-column-resizing.jsx

The TableColumnResizing plugin is now available in the "@devexpress/dx-react-grid-bootstrap3" and "@devexpress/dx-react-grid-material-ui" packages.
Use the following code to import the plugin.
```
import {
TableColumnResizing,
} from from '@devexpress/dx-react-grid-bootstrap3'/* or '@devexpress/dx-react-grid-material-ui' */;
```

refactor(react-grid): export of TableColumnResizing from theme packages

---

packages/dx-react-grid-bootstrap3/src/templates/table-detail-toggle-cell.jsx
packages/dx-react-grid-bootstrap3/src/templates/table-detail-toggle-cell.test.jsx
packages/dx-react-grid-material-ui/src/templates/table-detail-toggle-cell.jsx
packages/dx-react-grid-material-ui/src/templates/table-detail-toggle-cell.test.jsx

fix(react-grid): prevent click event propagation on detail toggle

---

packages/dx-react-grid/docs/guides/data-types.md
packages/dx-react-grid/docs/guides/plugin-overview.md

if add .md extension, in the document will get 404 page not found.

Correct grid reference url

---

packages/dx-grid-core/src/index.js
packages/dx-grid-core/src/utils/column.js
packages/dx-react-demos/src/bootstrap3/filtering/custom-filtering-algorithm.jsx
packages/dx-react-demos/src/material-ui/filtering/custom-filtering-algorithm.jsx
packages/dx-react-grid/docs/guides/filtering.md
packages/dx-react-grid/docs/reference/local-filtering.md
packages/dx-react-grid/src/plugins/local-filtering.jsx

In order to improve API consistency, we've decided to replace the `getColumnPredicate` function in the LocalFiltering plugin with the LocalFilteringColumnExtension.
Before:
```js
const columns = [{ name: 'field' }, { name: 'field2' }];
const fieldPredicate = /* custom filtering predicate */;
const getColumnPredicate = (columnName) => {
if (name === 'field') return fieldPredicate;
};
<Grid columns={columns}>
<LocalFiltering getColumnPredicate={getColumnPredicate} />
</Grid>
```
After:
```js
const columns= [{ name: 'field' }, { name: 'field2' }];
const fieldPredicate = /* custom filtering predicate */;
const localFilteringColumnExtensions = [
{ columnName: 'field', predicate: fieldPredicate },
];
<Grid columns={columns}>
<LocalFiltering …
```

refactor(react-grid): switch to column extensions in LocalFiltering

---

packages/dx-react-demos/src/bootstrap3/data-types/editors.jsx
packages/dx-react-demos/src/bootstrap3/data-types/formatters.jsx
packages/dx-react-demos/src/material-ui/data-types/editors.jsx
packages/dx-react-demos/src/material-ui/data-types/formatters.jsx
packages/dx-react-grid/docs/guides/data-types.md
packages/dx-react-grid/docs/reference/data-type-provider.md
packages/dx-react-grid/src/plugins/data-type-provider.jsx
packages/dx-react-grid/src/plugins/data-type-provider.test.jsx
packages/dx-react-grid/src/plugins/table.jsx

In order to simplify API, we changed the way the DataTypeProvider plugin detects columns associated with a type. Now, to associate a custom formatter and editor with a column, pass a column array to the DataTypeProvider's `for` field:
Before:
```js
const columns= [{ name: 'field', dataType: 'boolean' }, { name: 'field2' }];
<Grid columns={columns}>
<DataTypeProvider type="boolean" />
</Grid>
```
After:
```js
const columns= [{ name: 'field1' }, { name: 'field2' }];
const booleanColumns = ['field1'];
<Grid columns={columns}>
<DataTypeProvider for={booleanColumns} />
</Grid>
```

refactor(react-grid): specify typed columns directly in DataTypeProvider

---

packages/dx-react-demos/src/bootstrap3/data-accessors/custom-data-accessors-in-columns.jsx
packages/dx-react-demos/src/bootstrap3/data-accessors/custom-data-accessors.jsx
packages/dx-react-demos/src/bootstrap3/data-types/editors.jsx
packages/dx-react-demos/src/bootstrap3/editing/edit-row-controlled.jsx
packages/dx-react-demos/src/bootstrap3/editing/edit-row.jsx
packages/dx-react-demos/src/bootstrap3/featured-controlled-mode/demo.jsx
packages/dx-react-demos/src/bootstrap3/localization/basic.jsx
packages/dx-react-demos/src/material-ui/data-accessors/custom-data-accessors-in-columns.jsx
packages/dx-react-demos/src/material-ui/data-accessors/custom-data-accessors.jsx
packages/dx-react-demos/src/material-ui/data-types/editors.jsx
packages/dx-react-demos/src/material-ui/editing/edit-row-controlled.jsx
packages/dx-react-demos/src/material-ui/editing/edit-row.jsx
packages/dx-react-demos/src/material-ui/featured-controlled-mode/demo.jsx
packages/dx-react-demos/src/material-ui/localization/basic.jsx
packages/dx-react-grid/docs/reference/table-edit-column.md
packages/dx-react-grid/src/plugins/table-edit-column.jsx
packages/dx-react-grid/src/plugins/table-edit-column.test.jsx

We renamed the TableEditColumn plugin's  `allowAdding`, `allowEditing`, and `allowDeleting` properties to `showAddCommand`, `showEditCommand`, and `showDeleteCommand` to improve API clarity.
Before:
```js
<Grid>
<TableEditColumn allowAdding allowEditing allowDeleting />
</Grid>
```
After:
```js
<Grid>
<TableEditColumn showAddCommand showEditCommand showDeleteCommand />
</Grid>
```

refactor(react-grid): rename allow* to show*Command in TableEditColumn

---

packages/dx-grid-core/src/plugins/editing-state/reducers.js
packages/dx-grid-core/src/plugins/editing-state/reducers.test.js
packages/dx-grid-core/src/plugins/table-edit-row/computeds.js
packages/dx-grid-core/src/plugins/table-edit-row/computeds.test.js
packages/dx-react-demos/src/bootstrap3/data-types/editors.jsx
packages/dx-react-demos/src/bootstrap3/editing/edit-row-controlled.jsx
packages/dx-react-demos/src/bootstrap3/featured-controlled-mode/demo.jsx
packages/dx-react-demos/src/material-ui/data-types/editors.jsx
packages/dx-react-demos/src/material-ui/editing/edit-row-controlled.jsx
packages/dx-react-demos/src/material-ui/featured-controlled-mode/demo.jsx
packages/dx-react-grid/docs/guides/editing.md
packages/dx-react-grid/docs/reference/editing-state.md
packages/dx-react-grid/docs/reference/table-edit-row.md
packages/dx-react-grid/src/plugins/editing-state.jsx
packages/dx-react-grid/src/plugins/editing-state.test.jsx
packages/dx-react-grid/src/plugins/table-edit-row.jsx
packages/dx-react-grid/src/plugins/table-edit-row.test.jsx

The following EditingState plugin's properties have been renamed to improve the API consistency:
- `editingRows` => `editingRowIds`
- `defaultEditingRows` => `defaultEditingRowIds`
- `onEditingRowsChange` => `onEditingRowIdsChange`
The `editingRows` getter has been renamed to `editingRowIds`.

refactor(react-grid): rename the EditingState plugin properties

---

packages/dx-grid-core/src/plugins/editing-state/reducers.js
packages/dx-grid-core/src/plugins/editing-state/reducers.test.js
packages/dx-react-grid/docs/guides/editing.md
packages/dx-react-grid/docs/reference/editing-state.md
packages/dx-react-grid/docs/reference/table-edit-column.md
packages/dx-react-grid/src/plugins/editing-state.jsx

The following EditingState plugin's properties have been renamed to improve the API consistency:
- `deletedRows` => `deletedRowIds`
- `defaultDeletedRows` => `defaultDeletedRowIds`
- `onDeletedRowsChange` => `onDeletedRowIdsChange`
The `deletedRows` getter has been renamed to `deletedRowIds`.

refactor(react-grid): rename the deletedRows Getter and dependent properties

---

packages/dx-grid-core/src/plugins/integrated-grouping/computeds.js
packages/dx-react-grid/docs/reference/custom-grouping.md
packages/dx-react-grid/docs/reference/grouping-state.md
packages/dx-react-grid/docs/reference/integrated-grouping.md
packages/dx-react-grid/docs/reference/table-group-row.md
packages/dx-react-grid/src/plugins/custom-grouping.jsx
packages/dx-react-grid/src/plugins/custom-grouping.test.jsx
packages/dx-react-grid/src/plugins/grouping-state.jsx
packages/dx-react-grid/src/plugins/grouping-state.test.jsx
packages/dx-react-grid/src/plugins/table-group-row.jsx
packages/dx-react-grid/src/plugins/table-group-row.test.jsx

We changed the `expandedGroups` getter's data type from `Set` to `Array` to improve the API consistency.

refactor(react-grid): change the 'expandedGroups' Getter data type

---

packages/dx-react-grid/docs/reference/table-filter-row.md

fix(react-grid): correct TableFilterRow.CellProps types

---

packages/dx-react-grid-material-ui/src/templates/table-detail-toggle-cell.jsx
packages/dx-react-grid-material-ui/src/templates/table-detail-toggle-cell.test.jsx

fix(react-grid-material-ui): reverse detail toggle icons

---

.gitignore
packages/dx-react-grid-material-ui/src/templates/paging-panel/pagination.jsx

`dx-react-grid-material-ui`:
Pagination arrows In RTL layouts need to be rotated.

fix(react-grid-material-ui): rotate grid pagination arrows for RTL layouts

---

packages/dx-react-grid-demos/src/theme-sources/material-ui/components/progress-bar-cell.jsx
packages/dx-react-grid-material-ui/src/templates/table-header-cell/resizing-control.jsx

fix(react-grid-material-ui): get rid old palette syntax

---

packages/dx-react-core/src/plugin-based/helpers.js
packages/dx-vue-core/src/plugin-based/helpers.js

There is a difference between a variable being unset and not being declared at all.
```js
var asdf // unset variable
if (asdf) {
// nope
} else {
// executed
}
if (ddff) { // using of undeclared variable (exception is thrown)
// nope
} else {
// nope
}
if (typeof ddff !== 'undefined') {
// nope
} else {
// executed
}
```
I encountered the error in IE11.

fix(react-core) check for "Proxy"

---

packages/dx-react-chart/src/plugins/bar-series.jsx

Fix [1272](https://github.com/DevExpress/devextreme-reactive/issues/1272)

fix(react-chart): fix errors for BarSeries plugin

---

CHANGELOG.md
README.md
packages/dx-react-chart-demos/src/theme-registry.js
packages/dx-react-chart-material-ui/README.md
packages/dx-react-chart-material-ui/package.json
packages/dx-react-chart/docs/guides/plugin-overview.md
packages/dx-react-chart/docs/reference/palette.md
packages/dx-react-grid-demos/src/theme-registry.js
packages/dx-react-grid-material-ui/README.md
packages/dx-react-grid-material-ui/package.json
packages/dx-react-grid/docs/guides/getting-started.md
packages/dx-react-grid/docs/guides/plugin-overview.md
packages/dx-react-grid/docs/reference/table-column-resizing.md
packages/dx-react-grid/docs/reference/virtual-table.md
packages/dx-react-scheduler-demos/src/theme-registry.js
packages/dx-react-scheduler-material-ui/README.md
packages/dx-react-scheduler-material-ui/package.json
site/_posts/2017-01-01-10-react-theming.md
site/_posts/2017-01-01-40-react-features-set.md
site/react/grid/overrides/react-grid.html

I have recently added a backlink from Material-UI to your project in https://material-ui.netlify.com/demos/tables/#advanced-use-cases. In this process, I could notice some issues with the links and the wording used to refer to Material-UI. I took the time to address them.
I have also done a second commit where I add a backlink from your project to Material-UI. Let me know what you think about it.

 docs(material-ui): Use the official wording

---

packages/dx-grid-core/src/plugins/table-filter-row/helpers.js
packages/dx-grid-core/src/plugins/table-filter-row/helpers.test.js
packages/dx-react-grid/src/plugins/table-filter-row.jsx
packages/dx-react-grid/src/plugins/table-filter-row.test.jsx

fix(react-grid): use a column filter operation as a filter selector value

---

packages/dx-react-chart/src/plugins/pane-layout.jsx
packages/dx-react-chart/src/plugins/pane-layout.test.jsx
packages/dx-react-core/src/sizer.jsx

Restores `position: relative` on a `div` containing `svg`.

chore(react-chart): fix relative position in sizer

---

packages/dx-react-grid-demos/src/demo-sources/grid-basic/material-ui/table-template.jsx
packages/dx-react-scheduler-material-ui/src/templates/all-day-panel/cell.jsx
packages/dx-react-scheduler-material-ui/src/templates/views/horizontal/time-table/cell.jsx
packages/dx-react-scheduler-material-ui/src/templates/views/vertical/time-table/cell.jsx

NOTE: The `fade` function adds an alpha channel to color.

chore: remove deprecated theme MUI colors from the project

---

packages/dx-react-chart/docs/reference/area-series.md
packages/dx-react-chart/docs/reference/line-series.md
packages/dx-react-chart/docs/reference/spline-series.md
packages/dx-react-chart/src/plugins/area-series.jsx
packages/dx-react-chart/src/plugins/area-series.test.jsx
packages/dx-react-chart/src/plugins/line-series.jsx
packages/dx-react-chart/src/plugins/line-series.test.jsx
packages/dx-react-chart/src/plugins/spline-series.jsx
packages/dx-react-chart/src/plugins/spline-series.test.jsx
packages/dx-react-chart/src/templates/series/area.jsx
packages/dx-react-chart/src/templates/series/line.jsx
packages/dx-react-chart/src/templates/series/point-collection.jsx
packages/dx-react-chart/src/templates/series/spline.jsx
packages/dx-react-chart/src/utils/series-helper.jsx

Updates *LineSeries* and *SplineSeries* so that their *Path* components reflect corresponding difference.
Now `SplineSeries.Path` will render curved line.
Starting with this release, the *Area*, *Line*, and *Spline* series do not pass the `path` property to their `seriesComponent` component because it is an inner part of the component's implementation.
You can create *path* function using [d3.line](https://github.com/d3/d3-shape#line) and [d3.area](https://github.com/d3/d3-shape#area).

chore(react-chart): add Line and Spline series components

---

packages/dx-react-chart/src/plugins/axis.jsx
packages/dx-react-chart/src/plugins/axis.test.jsx
packages/dx-react-chart/src/templates/axis/root.jsx
packages/dx-react-chart/src/templates/axis/root.test.jsx

Keeps *div* ref in constructor.
Moves axis group alignment logic to Root component.

refactor(react-chart): make refs in Axis persistent

---

packages/dx-react-chart/src/plugins/axis.jsx
packages/dx-react-chart/src/plugins/axis.test.jsx

Makes `getBoundingClientRect` invocation to a time when axis is mount or updated.

refactor(react-chart): remove DOM access in Axis *render*

---

packages/dx-react-chart/src/plugins/hover-state.jsx
packages/dx-react-chart/src/plugins/tooltip.jsx
packages/dx-react-chart/src/utils/series-helper.jsx
packages/dx-react-chart/src/utils/series-helper.test.jsx

Makes plugins optionally dependent on *EventTracker* plugin.

chore(react-chart): fix HoverState and Tooltip plugins dependencies

---

packages/dx-chart-core/src/plugins/scale/computeds.js
packages/dx-chart-core/src/plugins/scale/computeds.test.js
packages/dx-chart-core/src/plugins/series/computeds.js
packages/dx-chart-core/src/plugins/series/computeds.test.js
packages/dx-react-chart-demos/src/demo-sources/chart-basic/animation.jsxt
packages/dx-react-chart-demos/src/demo-sources/chart-basic/bar-line.jsxt
packages/dx-react-chart-demos/src/demo-sources/chart-basic/combination-series.jsxt
packages/dx-react-chart-demos/src/demo-sources/chart-basic/group-bar.jsxt
packages/dx-react-chart-demos/src/demo-sources/chart-basic/typescript.tsxt
packages/dx-react-chart-demos/src/demo-sources/combination/bar-line.jsxt
packages/dx-react-chart/docs/reference/area-series.md
packages/dx-react-chart/docs/reference/bar-series.md
packages/dx-react-chart/docs/reference/line-series.md
packages/dx-react-chart/docs/reference/scatter-series.md
packages/dx-react-chart/docs/reference/spline-series.md
packages/dx-react-chart/src/utils/series-helper.jsx
packages/dx-react-chart/src/utils/series-helper.test.jsx

Previously, series bonded to the `ValueAxis` plugin using the `axisName` property. Now that property has been renamed `scaleName` because the series bonds to the `ValueScale` plugin.

chore(react-chart): rename `axisName` property to `scaleName` in series

---

packages/dx-chart-core/src/plugins/axis/computeds.js
packages/dx-chart-core/src/plugins/axis/computeds.test.js
packages/dx-chart-core/src/plugins/scale/computeds.js
packages/dx-chart-core/src/plugins/scale/computeds.test.js
packages/dx-react-chart-demos/src/demo-sources/chart-basic/animation.jsxt
packages/dx-react-chart-demos/src/demo-sources/chart-basic/combination-series.jsxt
packages/dx-react-chart-demos/src/demo-sources/chart-basic/typescript.tsxt
packages/dx-react-chart-demos/src/demo-sources/combination/bar-line.jsxt
packages/dx-react-chart/docs/reference/argument-axis.md
packages/dx-react-chart/docs/reference/value-axis.md
packages/dx-react-chart/src/plugins/axis.jsx
packages/dx-react-chart/src/plugins/axis.test.jsx

Previously, the `ValueAxis` plugin had the `name` property for binding to series. Now the property has been renamed to `scaleName` because the axes are bound to the `ValueScale` plugin.

refactor(react-chart): rename `name` property to `scaleName` in axes

---

packages/dx-chart-core/src/utils/event-tracker.js
packages/dx-chart-core/src/utils/event-tracker.test.js
packages/dx-chart-core/src/utils/hover-state.js
packages/dx-chart-core/src/utils/hover-state.test.js
packages/dx-chart-core/src/utils/series.js
packages/dx-chart-core/src/utils/series.test.js

Removes complex hover target picking logic. Now point belonging to the last declared series has priority unless its distance is not much greater than that of other candidates.
Tracker now operates with absolute distances rather than relative (like it did beforehand).

chore(react-chart): improve small targets tracking

---

packages/dx-react-chart-demos/src/demo-sources/chart-basic/animation.jsxt
packages/dx-react-chart-demos/src/demo-sources/chart-basic/combination-series.jsxt
packages/dx-react-chart-demos/src/demo-sources/chart-basic/typescript.tsxt
packages/dx-react-chart-demos/src/demo-sources/point-chart/scatter.jsxt
packages/dx-react-chart/docs/reference/argument-axis.md
packages/dx-react-chart/docs/reference/value-axis.md
packages/dx-react-chart/src/plugins/axis.jsx
packages/dx-react-chart/src/plugins/axis.test.jsx

The `showGrids` *Axis* property is renamed to `showGrid`.

refactor(react-chart): rename "showGrids" Axis property

---

packages/dx-react-chart-material-ui/src/templates/tooltip/overlay.jsx
packages/dx-react-chart-material-ui/src/templates/tooltip/overlay.test.jsx

Now *material-ui* tooltip's appearance and positioning are more similar to those in *bootstrap4*.

chore(react-chart-material-ui): replace Popoper with Popper

---

packages/dx-chart-core/src/plugins/scale/computeds.js
packages/dx-chart-core/src/plugins/scale/computeds.test.js
packages/dx-react-chart-demos/src/demo-sources/chart-basic/bar-line.jsxt
packages/dx-react-chart-demos/src/demo-sources/chart-basic/logarithm.jsxt
packages/dx-react-chart-demos/src/demo-sources/combination/multiple-axes.jsxt
packages/dx-react-chart-demos/src/demo-sources/line-chart/axes-types.jsxt
packages/dx-react-chart/docs/reference/argument-scale.md
packages/dx-react-chart/docs/reference/value-scale.md
packages/dx-react-chart/src/plugins/scale.jsx
packages/dx-react-chart/src/plugins/scale.test.jsx

Add `modifyDomain` scale property. Removes `min` and `max` scale properties.
The `min` and `max` scale properties are replaced with the `modifyDomain` property because the *band* scale domain cannot be customized in *min* and *max* terms.
Replace this
```javascript
<ArgumentScale min={0} max={10} ... />
```
with this
```javascript
const modifyDomain = () => [0, 10];
<ArgumentScale modifyDomain={modifyDomain} ... />
```

refactor(react-chart): property to customize scale domain

---

site/Gemfile
site/Gemfile.lock
site/_config.yml
site/_layouts/docs.html

I think we should add sitemap because
- algolia [advises](https://community.algolia.com/docsearch/recommended-configuration.html) add sitemap
- SEO advises add sitemap
About `priority` in sitemap https://github.com/jekyll/jekyll-sitemap/issues/196#issuecomment-341798669

chore(site): fix Algolia Docsearch

---

packages/dx-react-grid-bootstrap3/src/templates/table-container.jsx
packages/dx-react-grid-material-ui/src/templates/table-container.jsx
packages/dx-styles/dx-grid-bs4.css

fix(react-grid): stretch table container to a container size

---

packages/dx-chart-core/src/utils/event-tracker.js
packages/dx-chart-core/src/utils/event-tracker.test.js
packages/dx-react-chart/src/plugins/event-tracker.jsx

Handles *mousemove* and *mouseleave* events if either *pointer* or *touch* events are not available.

fix(react-chart): fix-event-handlers-in-safari

---

packages/dx-demo-shell/src/demo-viewer/demo-renderer.jsx

Required property explicitly specified as `undefined` is considered as absent. This PR adds default value for `DemoRenderer.perfSamplesCount` property.

chore: fix demo renderer default props

---

packages/dx-chart-core/src/plugins/axis/computeds.ts
packages/dx-chart-core/src/plugins/scale/computeds.test.ts
packages/dx-chart-core/src/plugins/scale/computeds.ts
packages/dx-chart-core/src/types/chart-core.types.ts
packages/dx-chart-core/src/types/plugins.scale.types.ts
packages/dx-react-chart/api/dx-react-chart.api.ts
packages/dx-react-chart/src/plugins/area-series.test.tsx
packages/dx-react-chart/src/plugins/axis.tsx
packages/dx-react-chart/src/plugins/bar-series.test.tsx
packages/dx-react-chart/src/plugins/chart-core.test.tsx
packages/dx-react-chart/src/plugins/chart-core.tsx
packages/dx-react-chart/src/plugins/line-series.test.tsx
packages/dx-react-chart/src/plugins/pie-series.test.tsx
packages/dx-react-chart/src/plugins/scale.test.tsx
packages/dx-react-chart/src/plugins/scatter-series.test.tsx
packages/dx-react-chart/src/plugins/spline-series.test.tsx
packages/dx-react-chart/src/utils/series-helper.test.tsx
packages/dx-react-chart/src/utils/series-helper.tsx

The **domains** *Getter* is moved from `ChartCore` to series component.
The behavior is changed as well. Previously all domains were built at once. Now domains are updated every time a series is added.

refactor(react-chart): move domains Getter to series component

---

packages/dx-react-chart-material-ui/package.json
packages/dx-react-grid-material-ui/package.json
packages/dx-react-scheduler-material-ui/package.json

I would like to enable a third-party component search for Material-UI components like Gatsby is doing it with its plugins page: https://www.gatsbyjs.org/plugins/.

Add material-ui to the list of npm keywords

---

packages/dx-chart-core/src/plugins/scale/computeds.test.ts
packages/dx-chart-core/src/plugins/scale/computeds.ts
packages/dx-chart-core/src/plugins/stack/computeds.test.ts
packages/dx-chart-core/src/plugins/stack/computeds.ts
packages/dx-chart-core/src/types/plugins.stack.types.ts
packages/dx-react-chart/src/plugins/stack.test.tsx
packages/dx-react-chart/src/plugins/stack.tsx

`getPointTransformer.getValueDomains` is removed.

chore(react-chart): fix stacks processing after "domains" Getter movement

---

packages/dx-chart-core/src/plugins/axis/computeds.test.ts
packages/dx-chart-core/src/plugins/axis/computeds.ts
packages/dx-chart-core/src/types/plugins.axis.types.ts
packages/dx-react-chart/src/plugins/axis.test.tsx
packages/dx-react-chart/src/plugins/axis.tsx

By scale range matches (almost) pane size and tick count is *10*.
When scale range is adjusted (because of any reasons) tick count should be adjusted as well.

chore(react-chart): calculate tick count from scale range to pane size ratio

---

packages/dx-chart-core/src/plugins/scale/computeds.ts
packages/dx-chart-core/src/plugins/viewport/computeds.test.ts
packages/dx-chart-core/src/plugins/viewport/computeds.ts
packages/dx-chart-core/src/utils/scale.test.ts
packages/dx-chart-core/src/utils/scale.ts

Band scale paddings are reset before bounds are scaled.

chore(react-chart): fix bar margins in viewport

---

packages/dx-chart-core/src/plugins/tooltip/computeds.test.ts
packages/dx-chart-core/src/plugins/tooltip/computeds.ts
packages/dx-chart-core/src/utils/event-tracker.test.ts
packages/dx-chart-core/src/utils/event-tracker.ts
packages/dx-chart-core/src/utils/root-offset.test.ts
packages/dx-chart-core/src/utils/root-offset.ts

Fixes https://github.com/DevExpress/devextreme-reactive/issues/1947.

fix(react-chart): fix event coordinates calculation in a scrolled container

---

packages/dx-react-chart-demos/src/demo-sources/bar-chart/bootstrap4/series-interaction.jsx
packages/dx-react-chart-demos/src/demo-sources/bar-chart/material-ui/series-interaction.jsx

The current (in *master*) version is actually correct and better than the new one. But due to a [side effect](https://github.com/DevExpress/devextreme-reactive/pull/1975#issuecomment-483631146) there are unexpected animations.

chore(react-chart): fix series remounting on tooltip update

---

packages/dx-react-core/src/plugin-based/template-placeholder.test.tsx
packages/dx-react-core/src/plugin-based/template-placeholder.tsx

Given a plugin
```jsx
const Tester = ({ data }) => (
<Plugin name="Tester">
<Template name="test">
<TemplatePlaceholder />
<div>{data}</div>
</Template>
</Plugin>
);
```
The content is changed from
```jsx
<Tester data={1} />
<Tester data={2} />
<Tester data={3} />
```
to
```jsx
<Tester data={1} />
<Tester data={2} />
```
The resulting markup is expected to change from
```jsx
<div>1</div>
<div>2</div>
<div>3</div>
```
to
```jsx
<div>1</div>
<div>2</div>
```
Though it actually is
```jsx
<div>1</div>
<div>2</div>
<div>2</div>
```
When *Tester (3)* is removed the *previous* state
```jsx
<TemplatePlaceholder /> (from 3)
<div>3</div>
```
is compared to the *next* state
```jsx
<TemplatePlaceholder /> (from 2)
<div>2</div>
```
As a result, *TemplatePlaceholder* element is taken from the …

chore(react-core): fix TemplatePlaceholder updating

---

packages/dx-core/src/plugin-host.ts
packages/dx-core/src/utils.test.ts
packages/dx-core/src/utils.ts
packages/dx-react-core/src/plugin-based/getter.test.tsx
packages/dx-react-core/src/plugin-based/plugin-indexer.tsx

`Plugin`, `Getter` and `Template` have internal objects (`this.plugin`) which ordered within `PluginHost` internal object (`this.plugins`) based on corresponding *positions*.
Position originates from component index within its parent children.
For this tree
```jsx
<PluginHost>
<PluginA />
<PluginC />
</PluginHost>
```
the list is the following
```js
[ A(0), C(1) ]
```
When tree changes to
```jsx
<PluginHost>
<PluginA />
<PluginB />
<PluginC />
</PluginHost>
```
`PluginB` is created (internal object is created and added to list) and `PluginC` is updated (index changes).
During `PluginB` creation its internal object is created and has position `(1)`. But `PluginC` is not updated by that moment and its internal object position is `(1)` too.
Such position collision is resolved in such a way …

fix(react-core): prevent Getter losing on Plugin adding

---

packages/dx-react-chart/src/plugins/zoom-pan.tsx
packages/dx-react-core/src/draggable/mouse-strategy.ts
packages/dx-react-core/src/index.ts

fix(react-chart): fix strange text artifacts during scrolling

---

packages/dx-react-grid-bootstrap3/src/templates/table-container.jsx
packages/dx-react-grid-bootstrap3/src/templates/table-container.test.jsx
packages/dx-react-grid-bootstrap4/src/templates/table-container.jsx
packages/dx-react-grid-bootstrap4/src/templates/table-container.test.jsx
packages/dx-react-grid-material-ui/src/templates/table-container.jsx
packages/dx-react-grid-material-ui/src/templates/table-container.test.jsx

fix(react-grid): prevent scrolling sticky header on Safari

---

packages/dx-grid-core/src/plugins/virtual-table-state/helpers.test.ts
packages/dx-grid-core/src/plugins/virtual-table-state/helpers.ts
packages/dx-react-grid/src/plugins/virtual-table/virtual-table-state.tsx

fix(react-grid): correct calculation of available row count in infninite scrolling mode

---

packages/dx-react-bootstrap4/components/popover.jsx
packages/dx-react-bootstrap4/components/popover.test.jsx
packages/dx-react-chart-bootstrap4/api/dx-react-chart-bootstrap4.api.md
packages/dx-react-chart-bootstrap4/src/plugins/tooltip.jsx
packages/dx-react-chart-bootstrap4/src/templates/tooltip/arrow.jsx
packages/dx-react-chart-bootstrap4/src/templates/tooltip/arrow.test.jsx
packages/dx-react-chart-bootstrap4/src/templates/tooltip/overlay.jsx
packages/dx-react-chart-bootstrap4/src/templates/tooltip/sheet.jsx
packages/dx-react-chart-bootstrap4/src/templates/tooltip/sheet.test.jsx
packages/dx-react-chart-demos/src/demo-sources/bar-chart/bootstrap4/side-by-side.jsx
packages/dx-react-chart-demos/src/demo-sources/bar-chart/material-ui/side-by-side.jsx
packages/dx-react-chart-material-ui/api/dx-react-chart-material-ui.api.md
packages/dx-react-chart-material-ui/src/plugins/tooltip.jsx
packages/dx-react-chart-material-ui/src/templates/tooltip/arrow.jsx
packages/dx-react-chart-material-ui/src/templates/tooltip/arrow.test.jsx
packages/dx-react-chart-material-ui/src/templates/tooltip/overlay.jsx
packages/dx-react-chart-material-ui/src/templates/tooltip/overlay.test.jsx
packages/dx-react-chart-material-ui/src/templates/tooltip/sheet.jsx
packages/dx-react-chart-material-ui/src/templates/tooltip/sheet.test.jsx
packages/dx-react-chart/api/dx-react-chart.api.md
packages/dx-react-chart/docs/reference/tooltip.md
packages/dx-react-chart/src/plugins/tooltip.test.tsx
packages/dx-react-chart/src/plugins/tooltip.tsx
packages/dx-react-chart/src/types/plugins.tooltip.types.ts

Fixes #2166 
Added `arrowComponent` and `sheetComponent` to customize background of the tooltip and its arrow.

fix(react-chart): fix tooltip customization

---

packages/dx-grid-core/src/plugins/virtual-table-state/helpers.test.ts
packages/dx-grid-core/src/plugins/virtual-table-state/helpers.ts
packages/dx-grid-core/src/types/virtual-table-state.types.ts
packages/dx-react-grid/api/dx-react-grid.api.md
packages/dx-react-grid/src/plugins/virtual-table/virtual-table-state.tsx

fix(react-grid): correct calculating start index of loading row for Infinite Scrolling

---

packages/dx-scheduler-core/src/utils.test.ts
packages/dx-scheduler-core/src/utils.ts

fix(scheduler-core): display recurrent appointments in the lower right corner of WeekView correctly

---

packages/dx-grid-core/src/plugins/table-summary-row/computeds.test.ts
packages/dx-grid-core/src/plugins/table-summary-row/computeds.ts
packages/dx-grid-core/src/types/summary.types.ts
packages/dx-react-grid/src/plugins/table-summary-row.test.tsx
packages/dx-react-grid/src/plugins/table-summary-row.tsx

fix(react-grid): add summary rows only if summary items are specified

---

packages/dx-react-grid-bootstrap3/src/templates/table-header-cell.jsx
packages/dx-react-grid-bootstrap4/src/templates/table-header-cell.jsx
packages/dx-react-grid-material-ui/src/templates/table-header-cell.jsx
packages/dx-react-grid/docs/reference/table-header-row.md

fix(react-grid): correct getCellWidth property's default value

---

packages/dx-scheduler-core/src/plugins/drag-drop-provider/helpers.ts
packages/dx-scheduler-core/src/plugins/editing-state/helpers.ts
packages/dx-scheduler-core/src/plugins/scheduler-core/computeds.ts
packages/dx-scheduler-core/src/utils.ts

fix(scheduler-core): get rid of different `new Date` behavior in Safari

---

packages/dx-react-grid-demos/src/demo-sources/grid-featured-data-editing/material-ui/demo.jsx

fix(react-grid-demos): correct displaying custom selector in Edge

---

packages/dx-react-scheduler-demos/src/demo-data/tasks.js
packages/dx-react-scheduler-demos/src/demo-sources/scheduler-featured-appearance-customization/material-ui/demo.jsx
packages/dx-react-scheduler-demos/src/demo-sources/scheduler-featured-redux-integration/material-ui/demo.jsx
packages/dx-react-scheduler-demos/src/demo-sources/scheduler-localization/material-ui/custom-formatting.jsx
packages/dx-react-scheduler-material-ui/src/templates/appointment-form/recurrence/layout.jsx
packages/dx-react-scheduler-material-ui/src/templates/appointment-tooltip/content.jsx
packages/dx-react-scheduler-material-ui/src/templates/appointment-tooltip/header.jsx
packages/dx-react-scheduler-material-ui/src/templates/appointment-tooltip/layout.jsx
packages/dx-react-scheduler-material-ui/src/templates/appointment/vertical-appointment.jsx
packages/dx-react-scheduler-material-ui/src/templates/confirmation-dialog/layout.jsx
packages/dx-react-scheduler-material-ui/src/templates/confirmation-dialog/layout.test.jsx
packages/dx-react-scheduler-material-ui/src/templates/date-navigator/navigation-button.jsx
packages/dx-react-scheduler-material-ui/src/templates/date-navigator/navigation-button.test.jsx
packages/dx-react-scheduler-material-ui/src/templates/date-navigator/open-button.jsx
packages/dx-react-scheduler-material-ui/src/templates/date-navigator/open-button.test.jsx
packages/dx-react-scheduler-material-ui/src/templates/edit-recurrence-menu/layout.jsx
packages/dx-react-scheduler-material-ui/src/templates/edit-recurrence-menu/layout.test.jsx
packages/dx-react-scheduler-material-ui/src/templates/layouts/vertical-view-layout.jsx
packages/dx-react-scheduler-material-ui/src/templates/layouts/vertical-view-layout.test.jsx
packages/dx-react-scheduler-material-ui/src/templates/today-button/today-button.jsx
packages/dx-react-scheduler-material-ui/src/templates/view-switcher/switcher.jsx
packages/dx-react-scheduler-material-ui/src/templates/views/horizontal/time-table/cell.jsx
packages/dx-react-scheduler-material-ui/src/templates/views/vertical/day-scale/cell.jsx

feat(react-scheduler): add mobile adaptability to the Scheduler

---

packages/dx-demo-shell/src/demo-viewer/demo-frame.jsx

Because a demo is in a iframe element, we can't select a component by React DevTools.
This change refer to https://github.com/facebook/react-devtools/issues/76.

chore: support React DevTools for demo page

---

packages/dx-react-scheduler/src/plugins/appointment-form.test.tsx
packages/dx-react-scheduler/src/plugins/appointment-form.tsx

fix(react-scheduler): open the AppointmentForm from AllDayPanel

---

packages/dx-react-grid-demos/src/demo-sources/grid-lazy-loading/remote-data.jsxt

fix(react-grid-demos): show nodata message after scrolling and filtering

---

packages/dx-grid-core/src/plugins/table-band-header/computeds.test.ts
packages/dx-grid-core/src/plugins/table-band-header/computeds.ts
packages/dx-grid-core/src/plugins/table-band-header/helpers.test.ts
packages/dx-grid-core/src/plugins/table-band-header/helpers.ts
packages/dx-grid-core/src/types/band-header.types.ts

fix(react-grid): split band columns with the same name but different parents

---

packages/dx-react-grid-demos/src/demo-sources/grid-virtual-scrolling/scroll-to-row.jsxt

Allow sorting only by the `name` column.
Get rid of sorting lables for other column (using `SortingState.columnExtensions`)

chore: correct scroll-to-row demo

---

packages/dx-react-grid/src/plugins/table-tree-column.test.tsx
packages/dx-react-grid/src/plugins/table-tree-column.tsx

fix(react-grid): allow to change "TableTreeColumn.for" property in runtime

---

packages/dx-react-grid-bootstrap3/api/dx-react-grid-bootstrap3.api.md
packages/dx-react-grid-bootstrap4/api/dx-react-grid-bootstrap4.api.md
packages/dx-react-grid-material-ui/api/dx-react-grid-material-ui.api.md
packages/dx-react-grid/api/dx-react-grid.api.md
packages/dx-react-grid/docs/reference/virtual-table.md
packages/dx-react-grid/src/types/tables/virtual-table.types.ts

fixes #2659 
It is type-safe now to assign a ref to the VirtualTable plugin:
```typescript
const vtRef = useRef<typeof VirtualTable>(null);
```

fix(react-grid): add ref to VirtualTable props definition

---

packages/dx-react-chart/src/plugins/pane-layout.test.tsx
packages/dx-react-chart/src/plugins/pane-layout.tsx
packages/dx-react-chart/src/utils/updatable-sizer.test.tsx
packages/dx-react-chart/src/utils/updatable-sizer.tsx
packages/dx-react-core/src/sizer.test.tsx
packages/dx-react-core/src/sizer.tsx
packages/dx-react-grid/src/components/table-layout/virtual-table-layout.test.tsx
packages/dx-react-grid/src/components/table-layout/virtual-table-layout.tsx
packages/dx-react-grid/src/utils/grid-sizer.test.tsx
packages/dx-react-grid/src/utils/grid-sizer.tsx

fix(react-grid): prevent Sizer's infinite loop

---

packages/dx-react-scheduler/api/dx-react-scheduler.api.md
packages/dx-react-scheduler/docs/reference/appointment-form.md
packages/dx-react-scheduler/src/types/editing/appointment-form.types.ts
packages/dx-react-scheduler/src/types/index.ts
packages/dx-scheduler-core/src/plugins/appointment-form/utils.ts
packages/dx-scheduler-core/src/types/appointment-form.types.ts

Updated `AppointmentForm` `selectProps` documentation to detail the required shape of the `availableOptions` object. 
I was looking around for forever for this and had to dig into the code to find it eventually. 
Go open-source :wink: :thumbsup:

docs(react-scheduler): add description to AppointmentForm Select's availableOptions

---

packages/dx-react-scheduler-material-ui/src/templates/views/vertical/day-scale/cell.jsx
packages/dx-react-scheduler-material-ui/src/templates/views/vertical/day-scale/cell.test.jsx

feat(react-scheduler-material-ui): change DayView and WeekView DayScale's today cell appearance

---

packages/dx-scheduler-core/src/plugins/resources/computeds.test.ts
packages/dx-scheduler-core/src/plugins/resources/computeds.ts

fix(scheduler-core): assign colors to resource instances even when palette's size is less than the number of resource instances

---

packages/dx-scheduler-core/src/utils.test.ts
packages/dx-scheduler-core/src/utils.ts

fix(scheduler-core): filter WeekView appointments correctly when excluded days contain an interval of three or more days in a row

---

packages/dx-grid-core/src/plugins/table-summary-row/computeds.test.ts
packages/dx-grid-core/src/plugins/table-summary-row/computeds.ts
packages/dx-grid-core/src/plugins/table-summary-row/helpers.ts

fix(react-grid): avoid rendering group summary row if no footer summary exists

---

packages/dx-chart-core/src/plugins/zoom-and-pan/computeds.ts
packages/dx-chart-core/src/types/chart-core.types.ts
packages/dx-react-chart/api/dx-react-chart.api.md

fix(react-chart): make ArgumentScale factory type compatible with d3-scale

---

.circleci/config.yml
packages/dx-grid-core/src/plugins/integrated-summary/computeds.test.ts
packages/dx-grid-core/src/plugins/integrated-summary/computeds.ts

fix(grid-core): prevent values from being calculated twice in a group summary

---

packages/dx-react-grid/src/components/table-layout/virtual-table-layout.test.tsx
packages/dx-react-grid/src/components/table-layout/virtual-table-layout.tsx

Fixes #2863 
Fix regression after #2787
Issue #2749 resolves by correct filling container (see [docs](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/virtual-scrolling/#fill-the-container)). [Example](https://codesandbox.io/s/sad-dawn-rqutn?file=/index.html).

fix(react-grid): prevent collapse VirtualTable with horizontal scrolling

---

.github/semantic.yml
packages/dx-react-grid-export/api/dx-react-grid-export.api.md
packages/dx-react-grid-export/src/types/export/exporter.types.ts
packages/dx-react-grid/docs/reference/export-panel.md
packages/dx-react-grid/docs/reference/grid-exporter.md

fix(react-grid): define `ref` and `exportGrid` types in GridExporter

---

packages/dx-react-grid-material-ui/src/templates/group-panel-item.jsx
packages/dx-react-grid-material-ui/src/templates/group-panel-item.test.jsx

fix(react-grid-material-ui): center text when label without icon

---

packages/dx-grid-core/src/plugins/table-band-header/helpers.test.ts
packages/dx-grid-core/src/plugins/table-band-header/helpers.ts
packages/dx-grid-core/src/types/band-header.types.ts

fix(react-grid): correct columns on remove banded column in runtime

---

packages/dx-react-grid-material-ui/src/templates/table-fixed-cell.jsx

fix(react-grid-material-ui): Make border for fixed cells nontransparent

---

packages/dx-react-core/src/draggable/mouse-strategy.test.tsx
packages/dx-react-core/src/draggable/mouse-strategy.ts

fix(react-core): prevent errors when mouse drags element outside the window

---

packages/dx-react-grid/src/plugins/grouping-panel.test.tsx
packages/dx-react-grid/src/plugins/grouping-panel.tsx
packages/dx-react-grid/src/plugins/search-panel.test.tsx
packages/dx-react-grid/src/plugins/search-panel.tsx
packages/dx-react-grid/src/plugins/virtual-table/virtual-table-state.test.tsx
packages/dx-react-grid/src/plugins/virtual-table/virtual-table-state.tsx

fix(react-grid): reset viewport position on search and group when data remote

---

packages/dx-grid-core/src/plugins/table-summary-row/computeds.test.ts
packages/dx-grid-core/src/plugins/table-summary-row/computeds.ts
packages/dx-grid-core/src/types/summary.types.ts
packages/dx-react-grid/docs/reference/summary-state.md
packages/dx-react-grid/src/plugins/summary-state.test.tsx
packages/dx-react-grid/src/plugins/summary-state.tsx
packages/dx-react-grid/src/plugins/table-summary-row.test.tsx
packages/dx-react-grid/src/plugins/table-summary-row.tsx

fix(react-grid): allow to use SummaryState without "*Items" properties

---

packages/dx-grid-core/src/plugins/table-band-header/helpers.test.ts
packages/dx-grid-core/src/plugins/table-band-header/helpers.ts
packages/dx-react-grid/docs/reference/table-band-header.md
packages/dx-react-grid/src/plugins/table-band-header.tsx

Fixes #2963
The `TableColumnVisibility` plugin must now be declared **before** the `TableBandHeader` plugin. This is required to correctly calculate column spans and borders.
```diff
...
+<TableColumnVisibility
+  defaultHiddenColumnNames={...}
+/>
...
<TableBandHeader
columnBands={columnBands}
/>
...
-<TableColumnVisibility
-  defaultHiddenColumnNames={...}
-/>
...
```

fix(react-grid): make TableBandHeader work correctly with TableColumnVisibility

---

packages/dx-react-scheduler/src/plugins/current-time-indicator.test.tsx
packages/dx-react-scheduler/src/plugins/current-time-indicator.tsx

fix(react-scheduler): change the implementation of the CurrentTimeIndicator plugin set and clearInterval usage

---

packages/dx-grid-core/src/plugins/table-group-row/computeds.test.ts
packages/dx-grid-core/src/plugins/table-group-row/computeds.ts
packages/dx-grid-core/src/plugins/table-group-row/helpers.test.ts
packages/dx-grid-core/src/plugins/table-group-row/helpers.ts
packages/dx-grid-core/src/types/grouping.types.ts
packages/dx-react-grid/src/plugins/table-group-row.test.tsx
packages/dx-react-grid/src/plugins/table-group-row.tsx

fix(react-grid): correct colspan calculating for group row when used with certain plugins

---

packages/dx-react-grid-demos/src/theme-sources/material-ui/components/currency-type-provider.jsx

Fix [demo](https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/data-editing/).
Before:
After:

fix(react-grid): format currency in the Data Editing demo

---

packages/dx-grid-core/src/plugins/custom-tree-data/computeds.ts
packages/dx-grid-core/src/types/tree-data.types.ts
packages/dx-react-grid-demos/src/demo-sources/grid-tree-data/max-call-stack-test.jsxt

fix(react-grid): make tree data work with a high level of row nesting

---

packages/dx-grid-core/src/plugins/table-inline-cell-editing/computeds.test.ts
packages/dx-grid-core/src/plugins/table-inline-cell-editing/computeds.ts

fix(react-grid): make inline cell editing works only with data rows

---

packages/dx-grid-core/src/plugins/table-group-row/helpers.test.ts
packages/dx-grid-core/src/plugins/table-group-row/helpers.ts

fix(react-grid): take into account flex columns for colspan calculating

---

packages/dx-grid-core/src/plugins/table-group-row/computeds.test.ts
packages/dx-grid-core/src/plugins/table-group-row/computeds.ts
packages/dx-grid-core/src/plugins/table-group-row/helpers.test.ts
packages/dx-grid-core/src/plugins/table-group-row/helpers.ts

fix(react-grid): fix colspan calculation

---

packages/dx-react-scheduler-material-ui/api/dx-react-scheduler-material-ui.api.md
packages/dx-react-scheduler/api/dx-react-scheduler.api.md
packages/dx-react-scheduler/docs/reference/day-view.md
packages/dx-react-scheduler/docs/reference/week-view.md
packages/dx-react-scheduler/src/types/views/base-view.types.ts
packages/dx-react-scheduler/src/types/views/day-view.types.ts
packages/dx-react-scheduler/src/types/views/vertical-view.types.ts
packages/dx-react-scheduler/src/types/views/week-view.types.ts

fix(react-scheduler): make `timeScaleTickCellComponent` property public

---

packages/dx-react-grid/src/plugins/table-band-header.tsx

Fixes #3397
Now, declare the `TableColumnVisibility` plug-in before the `TableBandHeader` plug-in to correctly calculate column spans and borders.
```diff
...
+<TableColumnVisibility
+  defaultHiddenColumnNames={...}
+/>
...
<TableBandHeader
columnBands={columnBands}
/>
...
-<TableColumnVisibility
-  defaultHiddenColumnNames={...}
-/>
...
```

fix(react-grid): add dependence in the TableBandHeader plugin

---

packages/dx-react-grid-bootstrap3/src/templates/table-header-cell/resizing-control.jsx
packages/dx-react-grid-bootstrap3/src/templates/table-header-cell/resizing-control.test.jsx
packages/dx-react-grid-bootstrap4/src/templates/table-header-cell/resizing-control.jsx
packages/dx-react-grid-bootstrap4/src/templates/table-header-cell/resizing-control.test.jsx
packages/dx-react-grid-material-ui/src/templates/table-header-cell/resizing-control.jsx
packages/dx-react-grid-material-ui/src/templates/table-header-cell/resizing-control.test.jsx

fix(react-grid): prevent resize of the column out the left side of window

---

packages/dx-react-scheduler/api/dx-react-scheduler.api.md
packages/dx-react-scheduler/docs/reference/edit-recurrence-menu.md
packages/dx-react-scheduler/src/types/editing/edit-recurrence-menu.types.ts

fix(react-scheduler): Add params for commit

---

.github/workflows/no-response.yml

This Github action is a replacement for the no-response bot, which is outdated now. See: https://github.com/probot/no-response

chore: create the no-response.yml config for a Github action

---

packages/dx-react-bootstrap4/components/popover.jsx
packages/dx-react-bootstrap4/components/popover.test.jsx
packages/dx-react-chart-bootstrap4/package.json
packages/dx-react-chart-bootstrap4/src/templates/tooltip/overlay.jsx
packages/dx-react-chart-bootstrap4/src/templates/tooltip/overlay.test.jsx
packages/dx-react-chart-demos/package.json
packages/dx-react-chart-demos/src/demo-sources/export/bootstrap4/demo.jsx
packages/dx-react-chart-material-ui/src/templates/tooltip/overlay.jsx
packages/dx-react-grid-bootstrap4/package.json
packages/dx-styles/dx-chart-bs4.scss
yarn.lock

Hi there!
With React 18 having been available for some time now, one thing holding back an upgrade is the version of Popper in use in the bootstrap4 packages here (since popper 1.x only declares compatibility with up to React 17).
Since Popper 2.x is both compatible with React 18 and [still exposes the render-props](https://popper.js.org/react-popper/v2/render-props/) for compatibility with the existing class-based components in here, is it possible / reasonable to update the package to the 2.x line?

chore: use react-popper 2.x in bootstrap4 packages (permits React 18 support)

---

scripts/publish-site.js

After some intermediate updates (possibly https://github.com/DevExpress/devextreme-reactive/pull/3632) the "publish:site" command fails with:
```
import { copySync, removeSync, readFileSync, writeFileSync } from 'fs-extra';
^^^^^^^^
SyntaxError: Named export 'copySync' not found. The requested module 'fs-extra' is a CommonJS module, which may not support all module.exports as named exports.
```
Consider upgrading the "fs-extra" dep in order to use native esm import.

ci: Destructuring fs-extra
